Description of CargaMembrana2DDistribuida
CargaMembrana2DDistribuida
PURPOSE
|______________________________________________________________________|
SYNOPSIS
This is a script file.
DESCRIPTION
|______________________________________________________________________|
|                                                                      |
|          TEFAME - Toolbox para Elementos Finitos y Analisis          |
|                  Matricial de Estructuras en MATLAB                  |
|                                                                      |
|                   Area  de Estructuras y Geotecnia                   |
|                   Departamento de Ingenieria Civil                   |
|              Facultad de Ciencias Fisicas y Matematicas              |
|                         Universidad de Chile                         |
|                                                                      |
| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
| visualizar  la respuesta de sistemas  estructurales usando el metodo |
| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
| Repositorio: https://github.com/ppizarror/TEFAME                     |
|______________________________________________________________________|
|                                                                      |
| Clase CargaMembrana2DDistribuida                                       |
|                                                                      |
| Este archivo contiene la definicion de CargaMembrana2DDistribuida      |
| CargaMembrana2DDistribuida es una subclase de la clase Carga y         |
| corresponde a la representacion de una carga distribuida en un       |
| elemento tipo Membrana2D.                                              |
|                                                                      |
| La clase CargaMembrana2DDistribuida es una clase que contiene el       |
| elemento al que se le va a aplicar la carga, los nodos al que se     |
| aplica las cargas y las distancias de las dos cargas.                |
|______________________________________________________________________|
|                                                                      |
| MIT License                                                          |
| Copyright (c) 2018-2019 Pablo Pizarro R @ppizarror.com.              |
|                                                                      |
| Permission is hereby granted, free of charge, to any person obtai-   |
| ning a copy of this software and associated documentation files (the |
| "Software"), to deal in the Software without restriction, including  |
| without limitation the rights to use, copy, modify, merge, publish,  |
| distribute, sublicense, and/or sell copies of the Software, and to   |
| permit persons to whom the Software is furnished to do so, subject   |
| to the following conditions:                                         |
|                                                                      |
| The above copyright notice and this permission notice shall be       |
| included in all copies or substantial portions of the Software.      |
|                                                                      |
| THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      |
| EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF   |
| MERCHANTABILITY,FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.|
| IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY |
| CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, |
| TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE    |
| SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.               |
|______________________________________________________________________|
  Methods(Access=public):
       obj = CargaMembrana2DDistribuida(etiquetaCarga,elemObjeto,nodo1,nodo2,carga1,distancia1,carga2,distancia2)
       aplicarCarga(obj,factorDeCarga)
       disp(obj)
  Methods SuperClass (CargaEstatica):
       masa = obtenerMasa(obj)
       definirFactorUnidadMasa(obj,factor)
       definirFactorCargaMasa(obj,factor)
       nodos = obtenerNodos(obj)
  Methods SuperClass (ComponenteModelo):
       etiqueta = obtenerEtiqueta(obj)
       e = equals(obj,obj)
       objID = obtenerIDObjeto(obj)
CROSS-REFERENCE INFORMATION
This function calls:
CargaEstatica |______________________________________________________________________|
CargaMembrana2DDistribuida |______________________________________________________________________|
dispMetodoTEFAME dispMetodoTEFAME: Normaliza la salida estandar disp en consola de los
This function is called by:
CargaMembrana2DDistribuida |______________________________________________________________________|