Description of AnalisisEstatico
AnalisisEstatico
PURPOSE
______________________________________________________________________
SYNOPSIS
This is a script file.
DESCRIPTION
 ______________________________________________________________________
|                                                                      |
|           TEFAME - Toolbox para Elementos Finitos y Analisis         |
|                  Matricial de Estructuras en MATLAB                  |
|                                                                      |
|                   Area  de Estructuras y Geotecnia                   |
|                   Departamento de Ingenieria Civil                   |
|              Facultad de Ciencias Fisicas y Matematicas              |
|                         Universidad de Chile                         |
|                                                                      |
| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
| visualizar  la respuesta de sistemas  estructurales usando el metodo |
| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
| La plataforma es desarrollada en  propagacion orientada a objetos en |
| MATLAB.                                                              |
|______________________________________________________________________|
 ______________________________________________________________________
|                                                                      |
| Clase AnalisisEstatico                                               |
|                                                                      |
| Este archivo contiene la definicion de la Clase AnalisisEstatico     |
| AnalisisEstatico es una clase que se usa para resolver estaticamente |
| una  estructura  lineal y  elastica, sometida  a un  set de  cargas, |
| usando  el  metodo de  elementos finitos  y  analisis matricial  de  |
| estructuras.                                                         |
|                                                                      |
| Programado: FR                                                       |
| Fecha: 05/08/2015                                                    |
|                                                                      |
| Modificado por: FR - 24/10/2016                                      |
|                 Pablo Pizarro @ppizarror - 10/04/2019                |
|______________________________________________________________________|
  Properties (Access=private):
       numeroGDL
       Kt
       F
       u
  Methods:
       analisisObj = AnalisisEstatico(modeloObjeto)
       analizar(analisisObj)
       Cd = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
       Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
       definirNumeracionGDL(analisisObj)
       disp(analisisObj)
       ensamblarMatrizRigidez(analisisObj)
       ensamblarVectorFuerzas(analisisObj)
       F_Modelo = obtenerVectorFuerzas(analisisObj)
       K_Modelo = obtenerMatrizRigidez(analisisObj)
       numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
       plot(analisisObj)
       u_Modelo = obtenerDesplazamientos(analisisObj)
CROSS-REFERENCE INFORMATION
This function calls:
Analisis ______________________________________________________________________
AnalisisEstatico ______________________________________________________________________
dispMetodoTEFAME dispMetodoTEFAME: Normaliza la salida estandar disp en consola de los
This function is called by:
AnalisisEstatico ______________________________________________________________________
SUBFUNCTIONS
function analisisObj = AnalisisEstatico(modeloObjeto)
function definirNumeracionGDL(analisisObj)
function analizar(analisisObj, varargin)
function ensamblarMatrizRigidez(analisisObj)
function Cd = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
function Kdv = ensamblarMatrizRigidezDisipadores(analisisObj)
function ensamblarVectorFuerzas(analisisObj)
function numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
function K_Modelo = obtenerMatrizRigidez(analisisObj)
function Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
function Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
function F_Modelo = obtenerVectorFuerzas(analisisObj)
function u_Modelo = obtenerDesplazamientos(analisisObj)
function [limx, limy, limz] = obtenerLimitesDeformada(analisisObj, factor)
function plt = plot(analisisObj, varargin)
function disp(analisisObj)
SOURCE CODE
% ______________________________________________________________________
%|                                                                      |
%|           TEFAME - Toolbox para Elementos Finitos y Analisis         |
%|                  Matricial de Estructuras en MATLAB                  |
%|                                                                      |
%|                   Area  de Estructuras y Geotecnia                   |
%|                   Departamento de Ingenieria Civil                   |
%|              Facultad de Ciencias Fisicas y Matematicas              |
%|                         Universidad de Chile                         |
%|                                                                      |
%| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
%| visualizar  la respuesta de sistemas  estructurales usando el metodo |
%| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
%| La plataforma es desarrollada en  propagacion orientada a objetos en |
%| MATLAB.                                                              |
%|______________________________________________________________________|
% ______________________________________________________________________
%|                                                                      |
%| Clase AnalisisEstatico                                               |
%|                                                                      |
%| Este archivo contiene la definicion de la Clase AnalisisEstatico     |
%| AnalisisEstatico es una clase que se usa para resolver estaticamente |
%| una  estructura  lineal y  elastica, sometida  a un  set de  cargas, |
%| usando  el  metodo de  elementos finitos  y  analisis matricial  de  |
%| estructuras.                                                         |
%|                                                                      |
%| Programado: FR                                                       |
%| Fecha: 05/08/2015                                                    |
%|                                                                      |
%| Modificado por: FR - 24/10/2016                                      |
%|                 Pablo Pizarro @ppizarror - 10/04/2019                |
%|______________________________________________________________________|
%
%  Properties (Access=private):
%       numeroGDL
%       Kt
%       F
%       u
%  Methods:
%       analisisObj = AnalisisEstatico(modeloObjeto)
%       analizar(analisisObj)
%       Cd = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
%       Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
%       definirNumeracionGDL(analisisObj)
%       disp(analisisObj)
%       ensamblarMatrizRigidez(analisisObj)
%       ensamblarVectorFuerzas(analisisObj)
%       F_Modelo = obtenerVectorFuerzas(analisisObj)
%       K_Modelo = obtenerMatrizRigidez(analisisObj)
%       numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
%       plot(analisisObj)
%       u_Modelo = obtenerDesplazamientos(analisisObj)
classdef AnalisisEstatico < Analisis
    properties(Access = private)
        Kt % Matriz de rigidez del modelo
        F % Vector de fuerzas aplicadas sobre el modelo
        u % Vector con los desplazamientos de los grados de libertad del modelo
    end % properties AnalisisEstatico
    methods
        function analisisObj = AnalisisEstatico(modeloObjeto)
            % AnalisisEstatico: es el constructor de la clase AnalisisEstatico
            %
            % analisisObj = AnalisisEstatico(modeloObjeto)
            %
            % Crea un objeto de la clase AnalisisEstatico, y guarda el modelo,
            % que necesita ser analizado
            if nargin == 0
                modeloObjeto = [];
            end % if
            analisisObj = analisisObj@Analisis(modeloObjeto);
            analisisObj.numeroGDL = 0;
            analisisObj.Kt = [];
            analisisObj.u = [];
            analisisObj.F = [];
        end % AnalisisEstatico constructor
        function definirNumeracionGDL(analisisObj)
            % definirNumeracionGDL: es un metodo de la clase AnalisisEstatico que
            % se usa para definir como se enumeran los GDL en el modelo
            %
            % definirNumeracionGDL(analisisObj)
            %
            % Define y asigna la enumeracion de los GDL en el modelo
            fprintf('\tDefiniendo numeracion GDL\n');
            % Primero se aplican las restricciones al modelo
            analisisObj.modeloObj.aplicarRestricciones();
            % Extraemos los nodos para que sean enumerados
            nodoObjetos = analisisObj.modeloObj.obtenerNodos();
            numeroNodos = length(nodoObjetos);
            % Inicializamos en cero el contador de GDL
            contadorGDL = 0;
            for i = 1:numeroNodos
                gdlidNodo = nodoObjetos{i}.obtenerGDLID;
                % Si no es reaccion entonces se agrega como GDL
                for j = 1:length(gdlidNodo)
                    if (gdlidNodo(j) == -1)
                        contadorGDL = contadorGDL + 1;
                        gdlidNodo(j) = contadorGDL;
                    end % if
                end % for j
                nodoObjetos{i}.definirGDLID(gdlidNodo);
            end % for i
            % Guardamos el numero de GDL, es decir el numero de ecuaciones
            % del sistema
            analisisObj.numeroGDL = contadorGDL;
            % Extraemos los Elementos del modelo
            elementoObjetos = analisisObj.modeloObj.obtenerElementos();
            numeroElementos = length(elementoObjetos);
            % Definimos los GDLID en los elementos para poder formar la matriz de rigidez
            for i = 1:numeroElementos
                elementoObjetos{i}.definirGDLID();
            end % for i
        end % definirNumeracionGDL function
        function analizar(analisisObj, varargin)
            % analizar: es un metodo de la clase AnalisisEstatico que se usa para
            % realizar el analisis estatico
            % Analiza estaticamente el modelo lineal y elastico sometido a un
            % set de cargas
            %
            % analizar(analisisObj,varargin)
            %
            % Parametros opcionales:
            %   'factorCargaE'      Factor de cargas estaticas
            fprintf('Ejecuntando analisis estatico\n');
            % Define parametros
            p = inputParser;
            p.KeepUnmatched = true;
            addOptional(p, 'factorCargaE', 1);
            parse(p, varargin{:});
            r = p.Results;
            % Se definen los grados de libertad por nodo -> elementos
            analisisObj.definirNumeracionGDL();
            % Se aplica patron de carga
            analisisObj.modeloObj.aplicarPatronesDeCargasEstatico(r.factorCargaE);
            % Se calcula la matriz de rigidez
            analisisObj.ensamblarMatrizRigidez();
            % Guarda el resultado para las cargas estaticas
            fprintf('\tCalculando resultado carga estatica\n');
            analisisObj.ensamblarVectorFuerzas();
            analisisObj.u = (analisisObj.Kt^-1) * analisisObj.F;
            analisisObj.modeloObj.actualizar(analisisObj.u);
            % Termina el analisis
            analisisObj.analisisFinalizado = true;
            dispMetodoTEFAME();
        end % analizar function
        function ensamblarMatrizRigidez(analisisObj)
            % ensamblarMatrizRigidez: es un metodo de la clase AnalisisEstatico que se usa para
            % realizar el armado de la matriz de rigidez del modelo analizado
            %
            % ensamblarMatrizRigidez(analisisObj)
            %
            % Ensambla la matriz de Rigidez del modelo analizado usando el metodo
            % indicial
            fprintf('\tEnsamblando matriz de rigidez\n');
            analisisObj.Kt = zeros(analisisObj.numeroGDL, analisisObj.numeroGDL);
            % Extraemos los Elementos y Disipadores
            elementoObjetos = analisisObj.modeloObj.obtenerElementos();
            numeroElementos = length(elementoObjetos);
            % Definimos los GDLID en los elementos
            for i = 1:numeroElementos
                % Se obienen los gdl del elemento metodo indicial
                gdl = elementoObjetos{i}.obtenerGDLID();
                ngdl = elementoObjetos{i}.obtenerNumeroGDL();
                % Se obtiene la matriz de rigidez global del elemento-i
                k_globl_elem = elementoObjetos{i}.obtenerMatrizRigidezCoordGlobal();
                % Se calcula el metodo indicial
                for r = 1:ngdl
                    for s = 1:ngdl
                        i_ = gdl(r);
                        j_ = gdl(s);
                        % Si corresponden a grados de libertad -> puntos en (i,j)
                        % se suma contribucion metodo indicial
                        if (i_ ~= 0 && j_ ~= 0)
                            analisisObj.Kt(i_, j_) = analisisObj.Kt(i_, j_) + k_globl_elem(r, s);
                        end
                    end % for s
                end % for r
            end % for i
        end % ensamblarMatrizRigidez function
        function Cd = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
            % ensamblarMatrizAmortiguamientoDisipadores: Analisis Estatico
            % no soporta disipadores ya que estos responden a un caracter
            % dinamico, por tal se retorna una matriz de ceros
            %
            % Cd = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
            Cd = zeros(analisisObj.numeroGDL, analisisObj.numeroGDL);
        end % ensamblarMatrizAmortiguamientoDisipadores function
        function Kdv = ensamblarMatrizRigidezDisipadores(analisisObj)
            % ensamblarMatrizRigidezDisipadores: Analisis Estatico
            % no soporta disipadores ya que estos responden a un caracter
            % dinamico, por tal se retorna una matriz de ceros
            %
            % Kdv = ensamblarMatrizRigidezDisipadores(analisisObj)
            %
            % Ensambla la matriz de rigidez de los disipadores del modelo
            % analizado usando el metodo indicial
            Kdv = zeros(analisisObj.numeroGDL, analisisObj.numeroGDL);
        end % ensamblarMatrizRigidezDisipadores function
        function ensamblarVectorFuerzas(analisisObj)
            % ensamblarVectorFuerzas: es un metodo de la clase AnalisisEstatico que se usa para
            % realizar el armado del vector de fuerzas del modelo analizado
            %
            % ensamblarMatrizRigidez(analisisObj)
            %
            % Ensambla el vector de fuerzas del modelo analizado usando el metodo
            % indicial
            % En esta funcion se tiene que ensamblar el vector de fuerzas
            analisisObj.F = zeros(analisisObj.numeroGDL, 1);
            % Extraemos los nodos
            nodoObjetos = analisisObj.modeloObj.obtenerNodos();
            numeroNodos = length(nodoObjetos);
            % Definimos los GDLID en los nodos
            for i = 1:numeroNodos
                ngdlid = nodoObjetos{i}.obtenerNumeroGDL(); % Numero grados de libertad del nodo
                gdl = nodoObjetos{i}.obtenerGDLID(); % Grados de libertad del nodo
                reacc = nodoObjetos{i}.obtenerReacciones(); % Reacciones del nodo
                % Recorre cada grado de libertad, si no es cero entonces
                % hay una carga aplicada en ese grado de libertad para
                % lograr el equilibrio
                for j = 1:ngdlid
                    if (gdl(j) ~= 0)
                        analisisObj.F(gdl(j)) = -reacc(j);
                    end
                end % for j
            end % for i
        end % ensamblarVectorFuerzas function
        function numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
            % obtenerNumeroEcuaciones: es un metodo de la clase AnalisisEstatico
            % que se usa para obtener el numero total de GDL, es decir, ecuaciones
            % del modelo
            %
            % numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
            %
            % Obtiene el numero total de GDL (numeroEcuaciones) que esta guardado
            % en el Analisis (analisisObj)
            numeroEcuaciones = analisisObj.numeroGDL;
        end % obtenerNumeroEcuaciones function
        function K_Modelo = obtenerMatrizRigidez(analisisObj)
            % obtenerMatrizRigidez: es un metodo de la clase AnalisisEstatico
            % que se usa para obtener la matriz de rigidez del modelo
            %
            % K_Modelo = obtenerMatrizRigidez(analisisObj)
            %
            % Obtiene la matriz de rigidez (K_Modelo) del modelo que se genero
            % en el Analisis (analisisObj)
            K_Modelo = analisisObj.Kt;
        end % obtenerMatrizRigidez function
        function Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
            % obtenerMatrizAmortiguamientoDisipadores: es un metodo de la
            % clase que retorna la matriz de amortiguamiento de los disipadores
            %
            % Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
            %
            % Obtiene la matriz de amortiguamiento de los disipadores del modelo
            Cdv_Modelo = analisisObj.ensamblarMatrizAmortiguamientoDisipadores();
        end % obtenerMatrizAmortiguamientoDisipadores function
        function Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
            % obtenerMatrizRigidezDisipadores: es un metodo de la clase ModalEspectral
            % que se usa para obtener la matriz de rigidez de los
            % disipadores
            %
            % Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
            Kdv_Modelo = analisisObj.ensamblarMatrizRigidezDisipadores();
        end % obtenerMatrizRigidezDisipadores function
        function F_Modelo = obtenerVectorFuerzas(analisisObj)
            % obtenerVectorFuerzas: es un metodo de la clase AnalisisEstatico
            % que se usa para obtener el vector de fuerza del modelo
            %
            % F_Modelo = obtenerVectorFuerzas(analisisObj)
            %
            % Obtiene el vector de fuerza (F_Modelo) del modelo que se genero
            % en el Analisis (analisisObj)
            F_Modelo = analisisObj.F;
        end % obtenerVectorFuerzas function
        function u_Modelo = obtenerDesplazamientos(analisisObj)
            % obtenerDesplazamientos: es un metodo de la clase AnalisisEstatico
            % que se usa para obtener el vector de desplazamiento del modelo
            % obtenido del analisis
            %
            % u_Modelo = obtenerDesplazamientos(analisisObj)
            %
            % Obtiene el vector de desplazamiento (u_Modelo) del modelo que se
            % genero como resultado del Analisis (analisisObj)
            u_Modelo = analisisObj.u;
        end % obtenerDesplazamientos function
        function [limx, limy, limz] = obtenerLimitesDeformada(analisisObj, factor)
            % obtenerLimitesDeformada: Obtiene los limites de deformacion
            %
            % [limx,limy,limz] = obtenerLimitesDeformada(analisisObj, factor)
            factor = 1.25 * factor;
            limx = [inf, -inf];
            limy = [inf, -inf];
            limz = [inf, -inf];
            % Carga objetos
            nodoObjetos = analisisObj.modeloObj.obtenerNodos();
            numeroNodos = length(nodoObjetos);
            gdl = 2;
            for i = 1:numeroNodos
                coords = nodoObjetos{i}.obtenerCoordenadas();
                ngdlid = length(coords);
                gdl = max(gdl, ngdlid);
            end % for i
            elementoObjetos = analisisObj.modeloObj.obtenerElementos();
            numeroElementos = length(elementoObjetos);
            for i = 1:numeroElementos
                nodoElemento = elementoObjetos{i}.obtenerNodos();
                numNodo = length(nodoElemento);
                for j = 1:numNodo
                    coord = nodoElemento{j}.obtenerCoordenadas();
                    def = nodoElemento{j}.obtenerDesplazamientos();
                    if analisisObj.analisisFinalizado
                        coordi = coord + def .* factor;
                    else
                        coordi = coord;
                    end
                    limx(1) = min(limx(1), coordi(1));
                    limy(1) = min(limy(1), coordi(2));
                    limx(2) = max(limx(2), coordi(1));
                    limy(2) = max(limy(2), coordi(2));
                    if gdl == 3
                        limz(1) = min(limz(1), coordi(3));
                        limz(2) = max(limz(2), coordi(3));
                    end
                    if analisisObj.analisisFinalizado
                        coordf = coord - def .* factor;
                    else
                        coordf = coord;
                    end
                    limx(1) = min(limx(1), coordf(1));
                    limy(1) = min(limy(1), coordf(2));
                    limx(2) = max(limx(2), coordf(1));
                    limy(2) = max(limy(2), coordf(2));
                    if gdl == 3
                        limz(1) = min(limz(1), coordf(3));
                        limz(2) = max(limz(2), coordf(3));
                    end
                end % for j
            end % for i
        end % obtenerLimitesDeformada function
        function plt = plot(analisisObj, varargin)
            % plt: Grafica el modelo
            %
            % plt = plot(analisisObj,varargin)
            %
            % Parametros opcionales:
            %   'angAzh'        Angulo grafico 3d azimutal
            %   'angPol'        Angulo grafico 3d polar
            %   'defElem'       Dibuja la deformada de cada elemento
            %   'deformada'     Dibuja la deformada del problema
            %   'factor'        Factor de la deformada
            %   'lwElemD'       Ancho linea elemento deformado
            %   'lwElemE'       Ancho linea elemento estatico
            %   'sizeNodoD'     Porte nodo deformado
            %   'sizeNodoE'     Porte nodo estatico
            %   'styleElemD'    Estilo elemento deformado
            %   'styleElemE'    Estilo elemento estatico
            %   'styleNodoD'    Estilo nodo deformado
            %   'styleNodoE'    Estilo nodos estaticos
            %   'unidad'        Unidar longitud
            p = inputParser;
            p.KeepUnmatched = true;
            addOptional(p, 'angAzh', 45);
            addOptional(p, 'angPol', 45);
            addOptional(p, 'defElem', true);
            addOptional(p, 'deformada', false);
            addOptional(p, 'factor', 1);
            addOptional(p, 'lwElemD', 1.25);
            addOptional(p, 'lwElemE', 0.5);
            addOptional(p, 'sizeNodoD', 10);
            addOptional(p, 'sizeNodoE', 5);
            addOptional(p, 'styleElemD', 'k-');
            addOptional(p, 'styleElemE', 'b-');
            addOptional(p, 'styleNodoD', 'k');
            addOptional(p, 'styleNodoE', 'b');
            addOptional(p, 'unidad', 'm');
            parse(p, varargin{:});
            r = p.Results;
            % Obtiene valores
            deformada = r.deformada;
            factor = r.factor;
            defElem = r.defElem;
            % Grafica la estructura
            nodoObjetos = analisisObj.modeloObj.obtenerNodos();
            numeroNodos = length(nodoObjetos);
            % Calcula los limites
            [limx, limy, limz] = analisisObj.obtenerLimitesDeformada(factor);
            plt = figure('Name', sprintf('Plot %s', analisisObj.modeloObj.obtenerNombre()), ...
                'NumberTitle', 'off');
            if ~deformada
                title('Analisis Estatico');
            else
                title(sprintf('Analisis Estatico / Escala deformacion: %.2f', factor));
            end
            hold on;
            grid on;
            % Obtiene cuantos GDL tiene el modelo
            gdl = 2;
            ngdl = analisisObj.modeloObj.obtenerNumeroDimensiones();
            for i = 1:numeroNodos
                coords = nodoObjetos{i}.obtenerCoordenadas();
                ngdlid = length(coords);
                gdl = max(gdl, ngdlid);
                if ~deformada
                    nodoObjetos{i}.plot([], r.styleNodoE, r.sizeNodoE);
                end
            end % for i
            % Grafica los elementos
            elementoObjetos = analisisObj.modeloObj.obtenerElementos();
            numeroElementos = length(elementoObjetos);
            % Definimos los GDLID en los elementos
            for i = 1:numeroElementos
                % Se obienen los gdl del elemento metodo indicial
                nodoElemento = elementoObjetos{i}.obtenerNodos();
                numNodo = length(nodoElemento);
                elementoObjetos{i}.plot({}, r.styleElemE, r.lwElemE);
                if deformada && analisisObj.analisisFinalizado
                    def = cell(numNodo, 1);
                    for j = 1:numNodo
                        def{j} = factor * nodoElemento{j}.obtenerDesplazamientos();
                    end % for j
                    elementoObjetos{i}.plot(def, r.styleElemD, r.lwElemD, defElem);
                end
            end % for i
            % Grafica los nodos deformados
            if deformada && analisisObj.analisisFinalizado
                for i = 1:numeroNodos
                    coords = nodoObjetos{i}.obtenerCoordenadas();
                    def = nodoObjetos{i}.obtenerDesplazamientos();
                    for j = 1:length(def)
                        if isnan(def(j))
                            def(j) = 0;
                        end
                    end % for j
                    coords = coords + def .* factor;
                    ngdlid = length(coords);
                    gdl = max(gdl, ngdlid);
                    nodoObjetos{i}.plot(def.*factor, r.styleNodoD, r.sizeNodoD);
                end % for i
            end
            % Actualiza los ejes
            if limx(1) < limx(2)
                xlim(limx);
            end
            if limy(1) < limy(2)
                ylim(limy);
            end
            if gdl == 3 && limz(1) < limz(2)
                zlim(limz);
            end
            if ngdl == 2
                xlabel(sprintf('X (%s)', r.unidad));
                ylabel(sprintf('Y (%s)', r.unidad));
            else
                xlabel(sprintf('X (%s)', r.unidad));
                ylabel(sprintf('Y (%s)', r.unidad));
                zlabel(sprintf('Z (%s)', r.unidad));
                view(r.angAzh, r.angPol);
            end
        end % plot function
        function disp(analisisObj)
            % disp: es un metodo de la clase AnalisisEstatico que se usa para imprimir en
            % command Window la informacion del Analisis Estatico realizado
            %
            % disp(analisisObj)
            %
            % Imprime la informacion guardada en el AnalisisEstatico (analisisObj) en
            % pantalla
            fprintf('Propiedades analisis estatico:\n');
            fprintf('\tMatriz de Rigidez:\n');
            disp(analisisObj.Kt);
            fprintf('\tDeterminante: %f\n\n', det(analisisObj.Kt));
            fprintf('\tVector de Fuerzas:\n');
            disp(analisisObj.F);
            fprintf('\tVector de Desplazamientos:\n');
            disp(analisisObj.u);
            dispMetodoTEFAME();
        end % disp function
    end % methods AnalisisEstatico
end % class AnalisisEstatico