Description of ModalEspectral
ModalEspectral
PURPOSE
______________________________________________________________________
SYNOPSIS
This is a script file.
DESCRIPTION
 ______________________________________________________________________
|                                                                      |
|           TEFAME - Toolbox para Elementos Finitos y Analisis         |
|                  Matricial de Estructuras en MATLAB                  |
|                                                                      |
|                   Area  de Estructuras y Geotecnia                   |
|                   Departamento de Ingenieria Civil                   |
|              Facultad de Ciencias Fisicas y Matematicas              |
|                         Universidad de Chile                         |
|                                                                      |
| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
| visualizar  la respuesta de sistemas  estructurales usando el metodo |
| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
| La plataforma es desarrollada en  propagacion orientada a objetos en |
| MATLAB.                                                              |
|______________________________________________________________________|
 ______________________________________________________________________
|                                                                      |
| Clase ModalEspectral                                                 |
|                                                                      |
| Este archivo contiene la definicion de la Clase ModalEspectral       |
| ModalEspectral es una clase que se usa para resolver la estructura   |
| aplicando el metodo modal espectral. Para ello se calcula la matriz  |
| de masa y de rigidez.                                                |
|                                                                      |
| Programado: Pablo Pizarro @ppizarror                                 |
| Fecha: 18/03/2019                                                    |
|______________________________________________________________________|
  Properties (Access=private):
       analisisFinalizado
       cargarAnimacion
       condMatRot
       condMatT
       cPenzien
       cRayleigh
       F
       gdlCond
       Km
       Kt
       Lm
       Mm
       Mmeff
       Mmeffacum
       modeloObj
       mostrarDeformada
       Mt
       Mtotal
       numDG
       numDGReal
       numeroGDL
       numModos
       phiExt
       phin
       rm
       Tn
       u
       wn
  Methods:
       analisisObj = ModalEspectral(modeloObjeto)
       [esfmax,esf,maxp,dirk] = calcularEsfuerzosElemento(analisisObj,carga,elemento,direccion)
       activarCargaAnimacion(analisisObj)
       activarPlotDeformadaInicial(analisisObj)
       analizar(analisisObj,varargin)
       c = obtenerCargaEstatica(analisisObj,varargin)
       C_Modelo = obtenerMatrizAmortiguamiento(analisisObj,rayleigh)
       calcularCurvasEnergia(analisisObj,carga)
       calcularDesplazamientoDrift(analisisObj,xanalisis)
       calcularMomentoCorteBasal(analisisObj,carga)
       Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
       definirNumeracionGDL(analisisObj)
       desactivarCargaAnimacion(analisisObj)
       desactivarPlotDeformadaInicial(analisisObj)
       disp(analisisObj)
       F_Modelo = obtenerVectorFuerzas(analisisObj)
       K_Modelo = obtenerMatrizRigidez(analisisObj)
       Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
       M_Modelo = obtenerMatrizMasa(analisisObj)
       numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
       phi_Modelo = obtenerMatrizPhi(analisisObj)
       plot(analisisObj,varargin)
       plotEsfuerzosElemento(analisisObj,carga)
       plotTrayectoriaNodo(analisisObj,carga,nodo,direccion)
       r_Modelo = obtenerVectorInfluencia(analisisObj)
       u_Modelo = obtenerDesplazamientos(analisisObj)
       wn_Modelo = obtenerValoresPropios(analisisObj)
CROSS-REFERENCE INFORMATION
This function calls:
Analisis ______________________________________________________________________
ModalEspectral ______________________________________________________________________
calculoEigDirectaBarrido calculoEigIterDirecta: Calcula los valores y vectores propios del sistema
calculoEigEigs calculoEigEigs: Calcula los valores y vectores propios del sistema usando
calculoEigItSubespacio calculoEigItSubespacio: Calcula los valores y vectores propios del sistema
calculoEigIterDirecta calculoEigIterDirecta: Calcula los valores y vectores propios del sistema
calculoEigIterInvDesplazamiento calculoEigIterDirecta: Calcula los valores y vectores propios del sistema
allDivMod ALLDIVMOD Retorna verdadero si todos los elementos de y son divisibles por r.
arrayIntNum2str textCell = array2str(a,num) function that transform the array of number to a
arrayNum2str textCell = array2str(a,num) function that transform the array of number to a
arrayStr2str textCell = array2str(a,num) function that transform the array of string to a
drawVyLine DRAW VX LINE
gifPlayerGUI
padFillNum PADFILLNUM Full a number respect to
CargaDinamica ______________________________________________________________________
dispMetodoTEFAME dispMetodoTEFAME: Normaliza la salida estandar disp en consola de los
verificarVectorDireccion verificarVectorDireccion: Verifica que un vector direccion tenga sentido y
This function is called by:
ModalEspectral ______________________________________________________________________
SUBFUNCTIONS
function analisisObj = ModalEspectral(modeloObjeto)
function analizar(analisisObj, varargin)
function resolverCargasDinamicas(analisisObj, varargin)
function numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
function M_Modelo = obtenerMatrizMasa(analisisObj)
function C_Modelo = obtenerMatrizAmortiguamiento(analisisObj, rayleigh)
function K_Modelo = obtenerMatrizRigidez(analisisObj)
function Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
function Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
function r_Modelo = obtenerVectorInfluencia(analisisObj)
function F_Modelo = obtenerVectorFuerzas(analisisObj)
function u_Modelo = obtenerDesplazamientos(analisisObj)
function wn_Modelo = obtenerValoresPropios(analisisObj)
function phi_Modelo = obtenerMatrizPhi(analisisObj)
function plt = plot(analisisObj, varargin)
function guardarResultados(analisisObj, nombreArchivo, cargas)
function calcularDesplazamientoDrift(analisisObj, carga, xanalisis, varargin)
function calcularMomentoCorteBasal(analisisObj, carga, varargin)
function calcularCurvasEnergia(analisisObj, carga, varargin)
function e_v = calcularModosEnergia(analisisObj, carga, dispinfo)
function [esfmax, esf, maxp, dirk] = calcularEsfuerzosElemento(analisisObj, carga, elemento, direccion)
function plotEsfuerzosElemento(analisisObj, carga, elemento, direccion, varargin)
function plotTrayectoriaNodo(analisisObj, carga, nodo, direccion, varargin)
function activarCargaAnimacion(analisisObj)
function desactivarCargaAnimacion(analisisObj)
function activarPlotDeformadaInicial(analisisObj)
function desactivarPlotDeformadaInicial(analisisObj)
function disp(analisisObj)
function c = obtenerCargaEstatica(analisisObj, varargin)
function definirNumeracionGDL(analisisObj)
function calcularModalEspectral(analisisObj, nModos, betacR, modocR,
function ensamblarMatrizRigidez(analisisObj)
function ensamblarMatrizMasa(analisisObj)
function Cdv = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
function Kdv = ensamblarMatrizRigidezDisipadores(analisisObj)
function ensamblarVectorFuerzas(analisisObj)
function plotAnimado(analisisObj, deformada, modo, factor, phif, limx, limy, limz,
function [limx, limy, limz] = obtenerLimitesDeformada(analisisObj, modo, factor, defcarga, carga)
function def = obtenerDeformadaNodo(analisisObj, nodo, modo, gdl, defcarga, carga, tcarga)
function [Cortante, Momento, CBplot, MBplot, hplot] = calcularMomentoCorteBasalAcel(analisisObj, acel)
function ctitle = imprimirPropiedadesAnalisisCarga(analisisObj, carga)
SOURCE CODE
% ______________________________________________________________________
%|                                                                      |
%|          TEFAME - Toolbox para Elementos Finitos y Analisis          |
%|                  Matricial de Estructuras en MATLAB                  |
%|                                                                      |
%|                   Area  de Estructuras y Geotecnia                   |
%|                   Departamento de Ingenieria Civil                   |
%|              Facultad de Ciencias Fisicas y Matematicas              |
%|                         Universidad de Chile                         |
%|                                                                      |
%| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
%| visualizar  la respuesta de sistemas  estructurales usando el metodo |
%| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
%| La plataforma es desarrollada en  propagacion orientada a objetos en |
%| MATLAB.                                                              |
%|______________________________________________________________________|
% ______________________________________________________________________
%|                                                                      |
%| Clase ModalEspectral                                                 |
%|                                                                      |
%| Este archivo contiene la definicion de la Clase ModalEspectral       |
%| ModalEspectral es una clase que se usa para resolver la estructura   |
%| aplicando el metodo modal espectral. Para ello se calcula la matriz  |
%| de masa y de rigidez.                                                |
%|                                                                      |
%| Programado: Pablo Pizarro @ppizarror                                 |
%| Fecha: 18/03/2019                                                    |
%|______________________________________________________________________|
%
%  Properties (Access=private):
%       analisisFinalizado
%       cargarAnimacion
%       condMatRot
%       condMatT
%       cPenzien
%       cRayleigh
%       F
%       gdlCond
%       Km
%       Kt
%       Lm
%       Mm
%       Mmeff
%       Mmeffacum
%       modeloObj
%       mostrarDeformada
%       Mt
%       Mtotal
%       numDG
%       numDGReal
%       numeroGDL
%       numModos
%       phiExt
%       phin
%       rm
%       Tn
%       u
%       wn
%  Methods:
%       analisisObj = ModalEspectral(modeloObjeto)
%       [esfmax,esf,maxp,dirk] = calcularEsfuerzosElemento(analisisObj,carga,elemento,direccion)
%       activarCargaAnimacion(analisisObj)
%       activarPlotDeformadaInicial(analisisObj)
%       analizar(analisisObj,varargin)
%       c = obtenerCargaEstatica(analisisObj,varargin)
%       C_Modelo = obtenerMatrizAmortiguamiento(analisisObj,rayleigh)
%       calcularCurvasEnergia(analisisObj,carga)
%       calcularDesplazamientoDrift(analisisObj,xanalisis)
%       calcularMomentoCorteBasal(analisisObj,carga)
%       Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
%       definirNumeracionGDL(analisisObj)
%       desactivarCargaAnimacion(analisisObj)
%       desactivarPlotDeformadaInicial(analisisObj)
%       disp(analisisObj)
%       F_Modelo = obtenerVectorFuerzas(analisisObj)
%       K_Modelo = obtenerMatrizRigidez(analisisObj)
%       Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
%       M_Modelo = obtenerMatrizMasa(analisisObj)
%       numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
%       phi_Modelo = obtenerMatrizPhi(analisisObj)
%       plot(analisisObj,varargin)
%       plotEsfuerzosElemento(analisisObj,carga)
%       plotTrayectoriaNodo(analisisObj,carga,nodo,direccion)
%       r_Modelo = obtenerVectorInfluencia(analisisObj)
%       u_Modelo = obtenerDesplazamientos(analisisObj)
%       wn_Modelo = obtenerValoresPropios(analisisObj)
classdef ModalEspectral < Analisis
    properties(Access = private)
        cargarAnimacion % Carga la animacion del grafico una vez renderizado
        condMatRot % Matriz de condensacion rotacion
        condMatT % Matriz de condensacion T
        cPenzien % Matriz de amortiguamiento de Wilson-Penzien
        cRayleigh % Matriz de amortiguamiento de Rayleigh
        F % Vector de fuerzas aplicadas sobre el modelo
        gdlCond % Grados de libertad condensados
        Km % Matriz rigidez modal
        Kt % Matriz de rigidez del modelo
        Kteq % Matriz rigidez equivalente
        Lm % Factor de participacion modal
        Mm % Matriz masa modal
        Mmeff % Masa modal efectiva
        Mmeffacum % Masa modal efectiva acumulada
        mostrarDeformada % Muestra la posicion no deformada en los graficos
        Mt % Matriz de masa del modelo
        Mteq % Matriz masa equivalente
        Mtotal % Masa total del modelo
        numDG % Numero de ejes de analisis despues de condensar
        numDGReal % Numero de ejes de analisis antes de condensar
        numModos % Numero de modos del analisis
        phin % Vectores propios del sistema
        phinExt % Vector propio del sistema extendido considerando grados condensados
        rm % Vector influencia
        Tn % Periodos del sistema
        u % Vector con los desplazamientos de los grados de libertad del modelo
        wn % Frecuencias del sistema
    end % properties ModalEspectral
    methods(Access = public)
        function analisisObj = ModalEspectral(modeloObjeto)
            % ModalEspectral: es el constructor de la clase ModalEspectral
            %
            % analisisObj = ModalEspectral(modeloObjeto)
            %
            % Crea un objeto de la clase ModalEspectral, y guarda el modelo,
            % que necesita ser analizado
            if nargin == 0
                modeloObjeto = [];
            end % if
            analisisObj = analisisObj@Analisis(modeloObjeto);
            analisisObj.Kt = [];
            analisisObj.Mt = [];
            analisisObj.u = [];
            analisisObj.F = [];
            analisisObj.mostrarDeformada = false;
            analisisObj.cargarAnimacion = true;
        end % ModalEspectral constructor
        function analizar(analisisObj, varargin)
            % analizar: es un metodo de la clase ModalEspectral que se usa para
            % realizar el analisis estatico
            % Analiza estaticamente el modelo lineal y elastico sometido a un
            % set de cargas, requiere el numero de modos para realizar el
            % analisis y de los modos conocidos con sus beta
            %
            % analizar(analisisObj,varargin)
            %
            % Parametros opcionales:
            %   'condensar'         Aplica condensacion (true por defecto)
            %   'cpenzienBeta'      Vector amortiguamiento Cpenzien
            %   'factorCargaE'      Factor de cargas estaticas
            %   'nModos'            Numero de modos de analisis (obligatorio)
            %   'rayleighBeta'      Vector amortiguamientos de Rayleigh
            %   'rayleighDir'       Direccion amortiguamiento Rayleigh
            %   'rayleighModo'      Vector modos de Rayleigh
            %   'toleranciaMasa'    Tolerancia de la masa para la condensacion
            %   'valvecAlgoritmo'   'eigvc','itDir','matBarr','itInvDesp','itSubesp'
            %   'valvecTolerancia'  Tolerancia calculo valores y vectores propios
            % Define parametros
            p = inputParser;
            p.KeepUnmatched = true;
            addOptional(p, 'condensar', true);
            addOptional(p, 'cpenzienBeta', []);
            addOptional(p, 'factorCargaE', 1);
            addOptional(p, 'muIterDespl', 0.5);
            addOptional(p, 'nModos', 0);
            addOptional(p, 'rayleighBeta', []);
            addOptional(p, 'rayleighDir', []);
            addOptional(p, 'rayleighModo', []);
            addOptional(p, 'toleranciamasa', 0.001);
            addOptional(p, 'valvecAlgoritmo', 'eigs');
            addOptional(p, 'valvecTolerancia', 0.001);
            parse(p, varargin{:});
            r = p.Results;
            maxcond = r.toleranciamasa;
            if ~r.condensar
                maxcond = -1;
            end
            % Verifica que parametros obligatorios sean proporcionados
            if r.nModos <= 0
                error('Numero de modos invalido');
            end
            r.nModos = floor(r.nModos);
            if isempty(r.rayleighBeta)
                error('Vector amortiguamiento de Rayleigh no puede ser nulo');
            end
            if isempty(r.rayleighModo)
                error('Vector modo Rayleigh no puede ser nulo');
            end
            for i = 1:length(r.rayleighModo)
                if r.rayleighModo(i) <= 0
                    error('Vector Rayleigh modo mal definido');
                end
            end % for i
            if length(r.rayleighBeta) ~= length(r.rayleighModo) || ...
                    length(r.rayleighBeta) ~= length(r.rayleighDir)
                error('Vectores parametros Rayleigh deben tener igual dimension');
            end
            for i = 1:length(r.rayleighDir)
                if ~(r.rayleighDir(i) == 'h' || r.rayleighDir(i) == 'v')
                    error('Direccion amortiguamiento Rayleigh solo puede ser (h) horizonal o (v) vertical');
                end
            end % for i
            if isempty(r.cpenzienBeta)
                error('Vector amortiguamiento cpenzien no puede ser nulo');
            end
            if r.valvecTolerancia <= 0
                error('Tolerancia calculo valores y vectores propios no puede ser inferior o igual a cero');
            end
            fprintf('Ejecutando analisis modal espectral:\n');
            fprintf('\tParametros analisis:\n');
            fprintf('\t\tNumero de modos: %d\n', r.nModos);
            fprintf('\t\tAmortiguamiento Rayleigh:\n');
            s = arrayIntNum2str(r.rayleighModo);
            fprintf('\t\t\tModos:\t\t%s\n', [s{:}]);
            s = arrayNum2str(r.rayleighBeta);
            fprintf('\t\t\tBeta:\t\t%s\n', [s{:}]);
            s = arrayStr2str(r.rayleighDir);
            fprintf('\t\t\tDireccion:\t%s\n', [s{:}]);
            fprintf('\t\tAmortiguamiento cpenzien:\n');
            s = arrayNum2str(r.cpenzienBeta);
            fprintf('\t\t\tBeta:\t\t%s\n', [s{:}]);
            % Se definen los grados de libertad por nodo -> elementos
            analisisObj.definirNumeracionGDL();
            % Se aplica patron de carga
            analisisObj.modeloObj.aplicarPatronesDeCargasEstatico(r.factorCargaE);
            % Se calcula la matriz de rigidez
            analisisObj.ensamblarMatrizRigidez();
            % Se calcula la matriz de masa
            analisisObj.ensamblarMatrizMasa();
            % Guarda el resultado para las cargas estaticas
            fprintf('\tCalculando resultado carga estatica\n');
            analisisObj.ensamblarVectorFuerzas();
            analisisObj.u = (analisisObj.Kt^-1) * analisisObj.F;
            analisisObj.modeloObj.actualizar(analisisObj.u);
            % Calcula el metodo modal espectral
            analisisObj.calcularModalEspectral(r.nModos, r.rayleighBeta, ...
                r.rayleighModo, r.rayleighDir, r.cpenzienBeta, ...
                maxcond, r.valvecAlgoritmo, r.valvecTolerancia, ...
                r.muIterDespl);
            % Termina el analisis
            dispMetodoTEFAME();
        end % analizar function
        function resolverCargasDinamicas(analisisObj, varargin)
            % resolverCargasDinamicas: Resuelve las cargas dinamicas del
            % sistema
            %
            % resolverCargasDinamicas(analisisObj,varargin)
            %
            % Parametros opcionales:
            %   'activado'          Indica que se realiza el analisis
            %   'betaGrafico'       Indica si se grafica la variacion del amortiguamiento en cada iteracion
            %   'betaObjetivo'      Beta objetivo para el calculo de disipadores
            %   'cargaDisipador'    Carga objetivo disipador para el calculo de v0
            %   'cpenzien'          Usa el amortiguamiento de cpenzien (false por defecto)
            %   'disipadores'       Usa los disipadores en el calculo (false por defecto)
            %   'factorCargasD'     Factor de cargas dinamico
            %   'iterDisipador'     Numero de iteraciones para el calculo de disipadores
            %   'tolIterDisipador'  Tolerancia usada para las iteraciones del calculo de disipadores
            if ~analisisObj.analisisFinalizado
                error('No se puede resolver las cargas dinamicas sin haber analizado la estructura');
            end
            p = inputParser;
            p.KeepUnmatched = true;
            addOptional(p, 'activado', true);
            addOptional(p, 'betaGrafico', false);
            addOptional(p, 'betaObjetivo', 0);
            addOptional(p, 'cargaDisipador', false);
            addOptional(p, 'cpenzien', false);
            addOptional(p, 'disipadores', true);
            addOptional(p, 'factorCargasD', 1);
            addOptional(p, 'iterDisipador', 10);
            addOptional(p, 'tolIterDisipador', 0.001);
            parse(p, varargin{:});
            r = p.Results;
            % Chequea inconsistencias
            if ~r.activado
                return;
            end
            if r.disipadores
                if ~isa(r.cargaDisipador, 'CargaDinamica')
                    error('No se ha definido cargaDisipador');
                end
                if r.iterDisipador < 0
                    error('El numero de iteraciones no puede ser menor a cero');
                end
                if r.tolIterDisipador <= 0
                    error('Tolerancia iteracion disipador invalida');
                end
            end
            fprintf('Metodo modal espectral:\n');
            analisisObj.modeloObj.aplicarPatronesDeCargasDinamico(r.cpenzien, r.disipadores, ...
                r.cargaDisipador, r.betaObjetivo, analisisObj.modeloObj.obtenerDisipadores(), ...
                r.iterDisipador, r.tolIterDisipador, r.betaGrafico, ...
                r.factorCargasD);
        end % resolverCargasDinamicas function
        function numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
            % obtenerNumeroEcuaciones: es un metodo de la clase ModalEspectral
            % que se usa para obtener el numero total de GDL, es decir, ecuaciones
            % del modelo
            %
            % numeroEcuaciones = obtenerNumeroEcuaciones(analisisObj)
            %
            % Obtiene el numero total de GDL (numeroEcuaciones) que esta guardado
            % en el Analisis (analisisObj)
            numeroEcuaciones = analisisObj.numeroGDL;
        end % obtenerNumeroEcuaciones function
        function M_Modelo = obtenerMatrizMasa(analisisObj)
            % obtenerMatrizMasa: es un metodo de la clase ModalEspectral
            % que se usa para obtener la matriz de masa del modelo
            %
            % M_Modelo = obtenerMatrizRigidez(analisisObj)
            %
            % Obtiene la matriz de masa (M_Modelo) del modelo que se genero
            % en el Analisis (analisisObj)
            M_Modelo = analisisObj.Mteq;
        end % obtenerMatrizMasa function
        function C_Modelo = obtenerMatrizAmortiguamiento(analisisObj, rayleigh)
            % obtenerMatrizAmortiguamiento: es un metodo de la clase ModalEspectral
            % que se usa para obtener la matriz de amortiguamiento del modelo
            %
            % C_Modelo = obtenerMatrizAmortiguamiento(analisisObj,rayleigh)
            %
            % Obtiene la matriz de amortiguamiento (C_Modelo) del modelo que se genero
            % en el Analisis (analisisObj)
            if rayleigh
                C_Modelo = analisisObj.cRayleigh;
            else
                C_Modelo = analisisObj.cPenzien;
            end
        end % obtenerMatrizAmortiguamiento function
        function K_Modelo = obtenerMatrizRigidez(analisisObj)
            % obtenerMatrizRigidez: es un metodo de la clase ModalEspectral
            % que se usa para obtener la matriz de rigidez del modelo
            %
            % K_Modelo = obtenerMatrizRigidez(analisisObj)
            %
            % Obtiene la matriz de rigidez (K_Modelo) del modelo que se genero
            % en el Analisis (analisisObj)
            K_Modelo = analisisObj.Kteq;
        end % obtenerMatrizRigidez function
        function Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
            % obtenerMatrizRigidez: es un metodo de la clase ModalEspectral
            % que se usa para obtener la matriz de amortiguamiento del modelo
            % producto de los disipadores incorporados
            %
            % Cdv_Modelo = obtenerMatrizAmortiguamientoDisipadores(analisisObj)
            %
            % Obtiene la matriz de amortiguamiento del modelo
            Cdv_Modelo = analisisObj.ensamblarMatrizAmortiguamientoDisipadores();
        end % obtenerMatrizAmortiguamientoDisipadores function
        function Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
            % obtenerMatrizRigidezDisipadores: es un metodo de la clase ModalEspectral
            % que se usa para obtener la matriz de rigidez de los
            % disipadores
            %
            % Kdv_Modelo = obtenerMatrizRigidezDisipadores(analisisObj)
            Kdv_Modelo = analisisObj.ensamblarMatrizRigidezDisipadores();
        end % obtenerMatrizRigidezDisipadores function
        function r_Modelo = obtenerVectorInfluencia(analisisObj)
            % obtenerVectorInfluencia: es un metodo de la clase ModalEspectral
            % que se usa para obtener el vector de influencia del modelo
            %
            % r_Modelo = obtenerVectorInfluencia(analisisObj)
            %
            % Obtiene el vector de influencia (r) del modelo que se genero
            % en el Analisis (analisisObj)
            r_Modelo = analisisObj.rm;
        end % obtenerVectorInfluencia function
        function F_Modelo = obtenerVectorFuerzas(analisisObj)
            % obtenerMatrizRigidez: es un metodo de la clase ModalEspectral
            % que se usa para obtener el vector de fuerza del modelo
            %
            % F_Modelo = obtenerVectorFuerzas(analisisObj)
            %
            % Obtiene el vector de fuerza (F_Modelo) del modelo que se genero
            % en el Analisis (analisisObj)
            F_Modelo = analisisObj.F;
        end % obtenerVectorFuerzas function
        function u_Modelo = obtenerDesplazamientos(analisisObj)
            % obtenerDesplazamientos: es un metodo de la clase ModalEspectral
            % que se usa para obtener el vector de desplazamiento del modelo
            % obtenido del analisis
            %
            % u_Modelo = obtenerDesplazamientos(analisisObj)
            %
            % Obtiene el vector de desplazamiento (u_Modelo) del modelo que se
            % genero como resultado del Analisis (analisisObj)
            u_Modelo = analisisObj.u;
        end % obtenerDesplazamientos function
        function wn_Modelo = obtenerValoresPropios(analisisObj)
            % obtenerValoresPropios: es un metodo de la clase ModalEspectral
            % que se usa para obtener los valores propios del modelo
            % obtenido del analisis
            %
            % w_Modelo = obtenerValoresPropios(analisisObj)
            %
            % Obtiene los valores propios (wn_Modelo) del modelo que se
            % genero como resultado del Analisis (analisisObj)
            wn_Modelo = analisisObj.wn;
        end % obtenerValoresPropios function
        function phi_Modelo = obtenerMatrizPhi(analisisObj)
            % obtenerMatrizPhi: es un metodo de la clase ModalEspectral
            % que se usa para obtener los vectores propios del modelo
            % obtenido del analisis
            %
            % phi_Modelo = obtenerMatrizPhi(analisisObj)
            %
            % Obtiene los vectores propios (phi_Modelo) del modelo que se
            % genero como resultado del Analisis (analisisObj)
            phi_Modelo = analisisObj.phin;
        end % obtenerMatrizPhi function
        function plt = plot(analisisObj, varargin)
            % plot: Grafica el modelo
            %
            % plt = plot(analisisObj,'var1',val1,'var2',val2)
            %
            % Parametros opcionales:
            %   '3dAngAzh'          Angulo azimutal grafico 3D
            %   '3dAngPol'          Angulo polar grafico 3D
            %   'colorDisipador'    Color del disipador
            %   'cuadros'           Numero de cuadros de la animacion
            %   'defElem'           Dibuja la deformada de cada elemento
            %   'disipador'         Dibuja los disipadores
            %   'factor'            Escala de la deformacion
            %   'gif'               Archivo en el que se guarda la animacion
            %   'lwDisipador'       Ancho linea disipador
            %   'lwElemD'           Ancho linea elemento dinamico
            %   'lwElemE'           Ancho linea elemento estatico
            %   'modo'              Numero de modo a graficar
            %   'mostrarEstatico'   Dibuja la estructura estatica al animar
            %   'sizeNodoE'         Porte nodo dinamico
            %   'sizeNodoE'         Porte nodo estatico
            %   'styleDisipador'    Estilo linea disipador
            %   'styleElemD'        Estilo elemento dinamico
            %   'styleElemE'        Estilo elemento estatico
            %   'styleNodoD'        Estilo nodo dinamico
            %   'styleNodoE'        Estilo nodo estatico
            %   'tmax'              Tiempo maximo al graficar cargas
            %   'tmin'              Tiempo minimo al graficar cargas
            %   'unidad'            Unidad de longitud
            % Establece variables iniciales
            fprintf('Generando animacion analisis modal espectral:\n');
            p = inputParser;
            p.KeepUnmatched = true;
            addOptional(p, 'angAzh', 45);
            addOptional(p, 'angPol', 45);
            addOptional(p, 'carga', false);
            addOptional(p, 'colorDisipador', 'r');
            addOptional(p, 'cuadros', 0);
            addOptional(p, 'defElem', false);
            addOptional(p, 'disipadores', true);
            addOptional(p, 'factor', 1);
            addOptional(p, 'gif', '');
            addOptional(p, 'lwDisipador', 1.3);
            addOptional(p, 'lwElemD', 1.2);
            addOptional(p, 'lwElemE', 0.5);
            addOptional(p, 'modo', 0);
            addOptional(p, 'mostrarEstatico', analisisObj.mostrarDeformada);
            addOptional(p, 'sizeNodoD', 10);
            addOptional(p, 'sizeNodoE', 5);
            addOptional(p, 'styleDisipador', '--');
            addOptional(p, 'styleElemD', 'k-');
            addOptional(p, 'styleElemE', 'b-');
            addOptional(p, 'styleNodoD', 'k');
            addOptional(p, 'styleNodoE', 'b');
            addOptional(p, 'tmax', -1);
            addOptional(p, 'tmin', 0);
            addOptional(p, 'unidad', 'm');
            parse(p, varargin{:});
            r = p.Results;
            modo = floor(r.modo);
            factor = r.factor;
            numCuadros = floor(r.cuadros);
            guardaGif = r.gif;
            defElem = r.defElem;
            carga = r.carga;
            defCarga = false; % Indica que la deformada se obtiene a partir de la carga
            mostrarEstatico = r.mostrarEstatico;
            disipadores = r.disipadores;
            % Tiempos
            tmin = max(0, r.tmin);
            tmax = r.tmax;
            tinicial = cputime;
            % Verificaciones si se grafica una carga
            if carga ~= false
                if ~(isa(carga, 'CargaDinamica') || isa(carga, 'CombinacionCargas'))
                    error('Solo se pueden graficar cargas dinamicas o combinaciones de cargas');
                end
                if isempty(carga.obtenerDesplazamiento())
                    error('No se ha resuelto la carga, no es posible graficar');
                end
                if modo ~= 0
                    error('No se puede graficar un modo y una carga de manera simultanea');
                end
                if numCuadros <= 0
                    error('Se debe especificar el numero de cuadros');
                end
                if tmax > carga.tAnalisis
                    fprintf('\tSe ha limitado el tiempo maximo de la carga a %.2fs\n', carga.tAnalisis);
                    tmax = carga.tAnalisis;
                elseif tmax < carga.tAnalisis
                    fprintf('\tLa carga se graficara a un tiempo menor que el computado originalmente\n');
                end
                if tmax <= 0
                    tmax = carga.tAnalisis;
                end
                if tmin >= tmax
                    error('El tiempo de analisis minimo no puede exceder al maximo');
                end
                % Compara los dt
                dt_plot = (tmax - tmin) / numCuadros;
                dt_real = carga.dt;
                % Si el dt del grafico es menor se reajustan los cuadros
                if dt_plot < dt_real
                    warning('El numero de cuadros genera un dt=%.3f inferior al dt=%.3f de la carga %s', ...
                        dt_plot, dt_real, carga.obtenerEtiqueta());
                    % Se limitan los cuadros
                    numCuadros = floor((tmax - tmin)/dt_real);
                    fprintf('\tSe ha limitado el numero de cuadros a %d\n', numCuadros);
                elseif dt_plot == dt_real
                    fprintf('\tEl numero de cuadros genera un dt igual al de la carga\n');
                else
                    fprintf('\tEl numero de cuadros genera un dt=%.3f superior al de la carga, superior en %.1f veces\n', ...
                        dt_plot, dt_plot/dt_real);
                    dt_plot_max_factor = 10; % Factor maximo de los cuadros
                    if dt_plot / dt_real > dt_plot_max_factor
                        fprintf('\t\tNo se recomienda que este factor exceda de %d, usar numero de cuadros igual a %d\n', ...
                            dt_plot_max_factor, floor((tmax - tmin)/(dt_plot_max_factor * dt_real)));
                    end
                end
                % Crea el vector de tiempos de analisis
                tCargaEq = linspace(tmin, tmax, numCuadros);
                % Busca las posiciones asociadas a la carga
                cargaTArr = linspace(0, carga.tAnalisis, carga.tAnalisis/carga.dt);
                tCargaPos = zeros(1, numCuadros); % Guarda los tiempos de 'snapshot' de la carga
                i = 1;
                for j = 1:length(cargaTArr)
                    if cargaTArr(j) >= tCargaEq(i)
                        tCargaPos(i) = j;
                        i = i + 1;
                    end
                    if i > numCuadros
                        break;
                    end
                end % for j
                % Activa la deformada por carga
                defCarga = true;
                fprintf('\tSe graficara la carga %s desde ti=%.3f a tf=%.3f con dt=%.3f\n', ...
                    carga.obtenerEtiqueta(), tmin, tmax, dt_plot);
            else
                % No se grafican cargas
                tCargaPos = zeros(1, numCuadros);
                tCargaEq = zeros(1, numCuadros);
            end
            % Chequea deformada
            deformada = false;
            modo = ceil(modo);
            if exist('modo', 'var') && modo > 0
                deformada = true;
            end
            deformada = deformada || defCarga;
            % Grafica la estructura si no se ha ejecutado el analisis
            if (~analisisObj.analisisFinalizado || modo <= 0) && ~defCarga
                plt = figure('Name', sprintf('Plot %s', analisisObj.modeloObj.obtenerNombre()), ...
                    'NumberTitle', 'off');
                movegui('center');
                hold on;
                grid on;
                [limx, limy, limz] = analisisObj.obtenerLimitesDeformada(0, factor, defCarga, carga);
                plotAnimado(analisisObj, false, 0, factor, 0, limx, limy, limz, ...
                    0, 1, 1, defElem, defCarga, carga, 1, tCargaEq, mostrarEstatico, disipadores, ...
                    r.styleNodoE, r.sizeNodoE, r.styleNodoD, r.sizeNodoD, r.styleElemE, r.lwElemE, ...
                    r.styleElemD, r.lwElemD, r.styleDisipador, r.colorDisipador, r.lwDisipador, ...
                    r.unidad, r.angAzh, r.angPol);
                figure(plt);
                return;
            end
            % Guarda gif
            guardarGif = false;
            if exist('guardaGif', 'var') && ~strcmp(guardaGif, '')
                guardarGif = true;
                guardaGif = sprintf(guardaGif, modo);
            else
                guardaGif = tempname;
            end
            if (modo > analisisObj.numModos || modo <= 0) && ~defCarga
                error('El modo a graficar %d excede la cantidad de modos del sistema (%d)', ...
                    modo, analisisObj.numModos);
            end
            % Obtiene el periodo
            if ~defCarga
                tn = analisisObj.Tn(modo);
            else
                tn = 0;
            end
            % Calcula los limites
            [limx, limy, limz] = analisisObj.obtenerLimitesDeformada(modo, factor, defCarga, carga);
            % Grafica la estructura
            if modo ~= 0
                fig_nom = sprintf('Plot %s - Modo %d', analisisObj.modeloObj.obtenerNombre(), ...
                    modo);
            else
                fig_nom = sprintf('Plot %s - Carga %s', analisisObj.modeloObj.obtenerNombre(), ...
                    carga.obtenerEtiqueta());
            end
            plt = figure('Name', fig_nom, 'NumberTitle', 'off');
            fig_num = get(gcf, 'Number');
            movegui('center');
            hold on;
            grid on;
            % axis tight manual;
            % set(gca, 'nextplot', 'replacechildren');
            % Imprime mensajes en consola
            if defElem
                fprintf('\tSe ha activado la deformada de los elementos\n');
            end
            if guardarGif && numCuadros ~= 0
                fprintf('\tEl proceso generara un archivo gif\n');
            end
            % Grafica el sistema
            if numCuadros <= 0
                fprintf('\tSe grafica el caso con la deformacion maxima\n');
                plotAnimado(analisisObj, deformada, modo, factor, 1, ...
                    limx, limy, limz, tn, 1, 1, defElem, defCarga, carga, ...
                    1, tCargaEq, mostrarEstatico, disipadores, r.styleNodoE, ...
                    r.sizeNodoE, r.styleNodoD, r.sizeNodoD, r.styleElemE, ...
                    r.lwElemE, r.styleElemD, r.lwElemD, r.styleDisipador, ...
                    r.colorDisipador, r.lwDisipador, r.unidad, ...
                    r.angAzh, r.angPol);
                fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
            else
                plotAnimado(analisisObj, deformada, modo, factor, 0, ...
                    limx, limy, limz, tn, 1, 1, defElem, defCarga, ...
                    carga, tCargaPos(1), tCargaEq, mostrarEstatico, disipadores, ...
                    r.styleNodoE, r.sizeNodoE, r.styleNodoD, r.sizeNodoD, ...
                    r.styleElemE, r.lwElemE, r.styleElemD, r.lwElemD, ...
                    r.styleDisipador, r.colorDisipador, r.lwDisipador, ...
                    r.unidad, r.angAzh, r.angPol);
                hold off;
                % Obtiene el numero de cuadros
                t = 0;
                dt = 2 * pi() / numCuadros;
                reverse_porcent = '';
                % Crea la estructura de cuadros
                Fr(numCuadros) = struct('cdata', [], 'colormap', []);
                for i = 1:numCuadros
                    % Si el usuario cierra el plot termina de graficar
                    if ~ishandle(plt) || ~ishghandle(plt)
                        delete(plt);
                        close(fig_num); % Cierra el grafico
                        fprintf('\n\tSe ha cancelado el proceso del grafico\n');
                        return;
                    end
                    t = t + dt;
                    try
                        % figure(fig_num); % Atrapa el foco
                        plotAnimado(analisisObj, deformada, modo, factor, sin(t), ...
                            limx, limy, limz, tn, i, numCuadros, defElem, defCarga, ...
                            carga, tCargaPos(i), tCargaEq, mostrarEstatico, disipadores, ...
                            r.styleNodoE, r.sizeNodoE, r.styleNodoD, r.sizeNodoD, ...
                            r.styleElemE, r.lwElemE, r.styleElemD, r.lwElemD, ...
                            r.styleDisipador, r.colorDisipador, r.lwDisipador, ...
                            r.unidad, r.angAzh, r.angPol);
                        drawnow;
                        Fr(i) = getframe(plt);
                        im = frame2im(Fr(i));
                        [imind, cm] = rgb2ind(im, 256);
                        if i == 1
                            imwrite(imind, cm, guardaGif, 'gif', 'Loopcount', inf, 'DelayTime', 0.1);
                        else
                            imwrite(imind, cm, guardaGif, 'gif', 'WriteMode', 'append', 'DelayTime', 0.1);
                        end
                    catch %#ok<*CTCH>
                        fprintf('\n\tSe ha cancelado el proceso del grafico\n');
                        return;
                    end
                    hold off;
                    msg = sprintf('\tGraficando ... %.1f/100', i/numCuadros*100);
                    fprintf([reverse_porcent, msg]);
                    reverse_porcent = repmat(sprintf('\b'), 1, length(msg));
                end % for i
                if guardarGif
                    fprintf('\n\tGuardando animacion gif en: %s\n', guardaGif);
                end
                % Imprime en consola el tiempo que se demoro el proceso
                fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
                % Reproduce la pelicula y cierra el grafico anterior
                close(fig_num);
                if analisisObj.cargarAnimacion
                    fprintf('\n\tAbriendo animacion\n');
                    try
                        gifPlayerGUI(guardaGif, 1/min(numCuadros, 60));
                    catch
                        error('Ha ocurrido un error al abrir el gif generado');
                    end
                else
                    fprintf('\n');
                end
                % Cierra la linea
                dispMetodoTEFAME();
            end
        end % plot function
        function guardarResultados(analisisObj, nombreArchivo, cargas)
            % guardarResultados: Guarda resultados adicionales del analisis
            %
            % guardarResultados(analisisObj,nombreArchivo,cargas)
            % Abre el archivo donde se guardara la informacion
            try
                archivoSalida = fopen(nombreArchivo, 'a');
            catch
                error('No se puede abrir el archivo %s', nombreArchivo);
            end
            % Chequea que cargas sea un cell de cargas dinamicas
            if ~exist('cargas', 'var') || isempty(cargas)
                error('Cargas debe ser un cell de cargas dinamicas no nulo');
            end
            % Chequea que cada elemento de cargas dinamicas sea una carga
            % dinamica
            for i=1:length(cargas)
                if ~isa(cargas{i}, 'CargaDinamica')
                    error('Elemento %d del cell de cargas no es un objeto de CargaDinamica', i);
                end
            end % for i
            fprintf('Calculando resultados analisis dinamico\n');
            fprintf(archivoSalida, '\n');
            fprintf(archivoSalida, '-------------------------------------------------------------------------------\n');
            fprintf(archivoSalida, 'Resultados del analisis dinamico\n');
            fprintf(archivoSalida, '-------------------------------------------------------------------------------\n');
            fprintf(archivoSalida, '\n');
            % Guarda las cargas maximas de los elementos
            elementos = analisisObj.modeloObj.obtenerElementos();
            % Estado
            totproc = length(elementos) * length(cargas);
            reverse_porcent = '';
            k = 1; % Contador total
            for i=1:length(elementos)
                fprintf(archivoSalida, 'Elemento: %s\n', elementos{i}.obtenerEtiqueta());
                % Recorre cada carga dinamica
                for j=1:length(cargas)
                    if ~cargas{j}.cargaCalculada()
                        fprintf(archivoSalida, '\tCarga %s no fue calculada\n', ...
                            cargas{j}.obtenerEtiqueta());
                        continue;
                    end
                    if ~cargas{j}.cargaCalculada()
                        fprintf(archivoSalida, '\tCarga %s no fue calculada\n', ...
                            cargas{j}.obtenerEtiqueta());
                        continue;
                    end
                    fprintf(archivoSalida, '\tCarga: %s\n', cargas{j}.obtenerEtiqueta());
                    elmEsf = analisisObj.calcularEsfuerzosElemento(cargas{j}, elementos{i}, 0);
                    elmEsf = arrayNum2str(elmEsf);
                    fprintf(archivoSalida, '\t\tEsfuerzos: %s\n', [elmEsf{:}]);
                    % Imprime estado
                    msg = sprintf('\tCalculando ... %.1f/100', k/totproc*100);
                    fprintf([reverse_porcent, msg]);
                    reverse_porcent = repmat(sprintf('\b'), 1, length(msg));
                    k = k + 1;
                end % for j
            end % for i
            fprintf('\n');
            dispMetodoTEFAME();
            % Cierra el archivo
            fclose(archivoSalida);
        end % guardarResultados function
        function calcularDesplazamientoDrift(analisisObj, carga, xanalisis, varargin)
            % calcularDesplazamientoDrift: Funcion que calcula el desplazamiento y
            % drift a partir de una carga
            %
            % calcularDesplazamientoDrift(analisisObj,carga,xanalisis,varargin)
            %
            % Parametros opcionales:
            %   'unidad'        Unidad de largo
            % Inicia proceso
            tinicial = cputime;
            % Define variables opcionales
            p = inputParser;
            p.KeepUnmatched = true;
            addOptional(p, 'unidad', 'm');
            parse(p, varargin{:});
            r = p.Results;
            % Verifica que la carga se haya calculado
            if ~(isa(carga, 'CargaDinamica') || isa(carga, 'CombinacionCargas'))
                error('Solo se pueden graficar cargas dinamicas o combinaciones de cargas');
            end
            desp = carga.obtenerDesplazamiento();
            if ~carga.cargaCalculada()
                error('La carga %s no se ha calculado', carga.obtenerEtiqueta());
            end
            fprintf('Calculando desplazamiento y drift:\n');
            ctitle = analisisObj.imprimirPropiedadesAnalisisCarga(carga);
            % Se genera vector en que las filas contienen nodos en un mismo piso,
            % rellenando con ceros la matriz en caso de diferencia de nodos por piso.
            % Tambien se genera vector que contiene alturas de piso
            nodos = analisisObj.modeloObj.obtenerNodos();
            nnodos = length(nodos);
            habs = zeros(1, 1);
            hNodos = zeros(1, 1);
            j = 1;
            k = 1;
            l = 1;
            ini = 1;
            ndrift = [];
            for i = 1:nnodos
                CoordNodo = nodos{i}.obtenerCoordenadas;
                xNodo = CoordNodo(1);
                yNodo = CoordNodo(2);
                if yNodo ~= habs(j)
                    k = 1;
                    j = j + 1;
                    habs(j, 1) = yNodo;
                    hNodos(j, k) = i;
                elseif i == 1
                    hNodos(j, k) = i;
                else
                    k = k + 1;
                    hNodos(j, k) = i;
                end
                if yNodo == 0
                    ini = ini + 1;
                end
                if xNodo == xanalisis
                    ndrift(l) = i; %#ok<AGROW>
                    l = l + 1;
                end
            end % for i
            [~, s] = size(desp);
            nndrift = length(ndrift);
            if isempty(ndrift)
                error('Posicion direccion analisis %.2f invalida', xanalisis);
            end
            despx = zeros(nndrift, s);
            driftx = zeros(nndrift-1, s);
            % Calculo de drift y desplazamiento en linea de analisis
            for i = 2:nndrift
                nodosup = ndrift(i);
                gdls = nodos{nodosup}.obtenerGDLIDCondensado();
                gdlx = gdls(1);
                despx(i, :) = desp(gdlx, :);
                driftx(i-1, :) = abs(despx(i, :)-despx(i-1, :)) ./ (habs(i) - habs(i-1));
            end % for i
            % Determinacion de envolvente maxima de desplazamiento y drift
            despxmax = max(abs(despx'))';
            driftxmax = max(abs(driftx'))';
            VecDesp = flipud(despxmax);
            VecDrift = flipud(driftxmax);
            hgen = flipud(habs);
            hplot = zeros(2*length(hgen), 1);
            Despplot = zeros(2*length(hgen)-1, 1);
            Driftplot = zeros(2*length(hgen)-1, 1);
            aux1 = 1;
            aux2 = 2;
            for i = 1:length(hgen)
                hplot(aux1, 1) = hgen(i);
                hplot(aux1+1, 1) = hgen(i);
                if aux2 <= 2 * length(hgen) - 1
                    Driftplot(aux2, 1) = VecDrift(i);
                    Driftplot(aux2+1, 1) = VecDrift(i);
                    Despplot(aux2, 1) = VecDesp(i);
                    Despplot(aux2+1, 1) = VecDesp(i);
                end
                aux1 = aux1 + 2;
                aux2 = aux2 + 2;
            end % for i
            hplot(length(hplot)) = [];
1000             % Crea las figuras
1001             fig_title = sprintf('Envolvente de Deriva Entre Piso - %s %s', ctitle, carga.obtenerEtiqueta());
1002             plt = figure('Name', fig_title, 'NumberTitle', 'off');
1003             movegui(plt, 'center');
1004             plot(Driftplot.*100, hplot, '*-', 'LineWidth', 1, 'Color', 'black');
1005             grid on;
1006             grid minor;
1007             xlabel('Drift (%)');
1008             ylabel(sprintf('Altura (%s)', r.unidad));
1009             title(fig_title);
1010
1011             fig_title = sprintf('Envolvente de Desplazamiento - %s %s', ctitle, carga.obtenerEtiqueta());
1012             plt = figure('Name', fig_title, 'NumberTitle', 'off');
1013             movegui(plt, 'center');
1014             plot(Despplot, hplot, '*-', 'LineWidth', 1, 'Color', 'black');
1015             grid on;
1016             grid minor;
1017             xlabel(sprintf('Desplazamiento (%s)', r.unidad));
1018             ylabel(sprintf('Altura (%s)', r.unidad));
1019             title(fig_title);
1020
1021             % Finaliza proceso
1022             drawnow();
1023             fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
1024             dispMetodoTEFAME();
1025
1026         end % calcularDesplazamientoDrift function
1027
1028         function calcularMomentoCorteBasal(analisisObj, carga, varargin)
1029             % calcularMomentoCorteBasal: Funcion que calcula el momento y
1030             % corte basal a partir de una carga
1031             %
1032             % calcularMomentoCorteBasal(analisisObj,carga,varargin)
1033             %
1034             % Parametros opcionales:
1035             %   'closeall'  Cierra todos los graficos
1036             %   'modo'      Vector con graficos de modos
1037             %   'plot'      'all','momento','corte','envmomento','envcorte'
1038             %   'unidadC'   Unidad corte del modelo
1039             %   'unidadM'   Unidad momento del modelo
1040
1041             % Inicia proceso
1042             tinicial = cputime;
1043             fprintf('Calculando grafico momento corte basal:\n');
1044
1045             % Rescata parametros
1046             p = inputParser;
1047             p.KeepUnmatched = true;
1048             addOptional(p, 'closeall', false);
1049             addOptional(p, 'modo', []);
1050             addOptional(p, 'plot', 'all');
1051             addOptional(p, 'unidadC', 'tonf');
1052             addOptional(p, 'unidadM', 'tonf-m');
1053             parse(p, varargin{:});
1054             r = p.Results;
1055             tipoplot = r.plot;
1056             envmodo = r.modo;
1057
1058             if r.closeall
1059                 close all;
1060             end
1061
1062             % Verifica que la carga se haya calculado
1063             if ~(isa(carga, 'CargaDinamica') || isa(carga, 'CombinacionCargas'))
1064                 error('Solo se pueden graficar cargas dinamicas o combinaciones de cargas');
1065             end
1066             acel = carga.obtenerAceleracion();
1067             if ~carga.cargaCalculada()
1068                 error('La carga %s no se ha calculado', carga.obtenerEtiqueta());
1069             end
1070             ctitle = analisisObj.imprimirPropiedadesAnalisisCarga(carga);
1071
1072             % Verifica que envmodo sea correcto
1073             [~, lphi] = size(analisisObj.phin);
1074             lenvmodo = length(envmodo);
1075             envmodo = sort(envmodo);
1076             for i = 1:lenvmodo
1077                 envmodo(i) = floor(envmodo(i));
1078                 if envmodo(i) < 0 || envmodo(i) > lphi
1079                     error('Analisis modo %d invalido', envmodo(i));
1080                 end
1081             end % for i
1082
1083             % Calcula el momento
1084             [Cortante, Momento, CBplot, MBplot, hplot] = analisisObj.calcularMomentoCorteBasalAcel(acel);
1085
1086             % Graficos
1087             t = carga.obtenerVectorTiempo(); % Vector de tiempo
1088             dplot = false; % Indica si se realizo algun grafico
1089
1090             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'corte')
1091                 fig_title = sprintf('Historial de Cortante Basal - %s %s', ctitle, carga.obtenerEtiqueta());
1092                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1093                 movegui(plt, 'center');
1094                 plot(t, Cortante(end, :), 'k-', 'LineWidth', 1);
1095                 grid on;
1096                 grid minor;
1097                 xlabel('Tiempo (s)');
1098                 ylabel(sprintf('Corte (%s)', r.unidadC));
1099                 title(fig_title);
1100                 dplot = true;
1101             end
1102
1103             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'momento')
1104                 fig_title = sprintf('Historial de Momento Basal - %s %s', ctitle, carga.obtenerEtiqueta());
1105                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1106                 movegui(plt, 'center');
1107                 plot(t, Momento(end, :), 'k-', 'LineWidth', 1);
1108                 grid on;
1109                 grid minor;
1110                 xlabel('Tiempo (s)');
1111                 ylabel(sprintf('Momento (%s)', r.unidadM));
1112                 title(fig_title);
1113                 dplot = true;
1114             end
1115
1116             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'envcorte')
1117                 fig_title = sprintf('Envolvente de Cortante Basal - %s %s', ctitle, carga.obtenerEtiqueta());
1118                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1119                 movegui(plt, 'center');
1120                 plot(CBplot, hplot, '*-', 'LineWidth', 1, 'Color', 'black');
1121                 hold on;
1122                 grid on;
1123                 grid minor;
1124                 xlabel(sprintf('Corte (%s)', r.unidadC));
1125                 ylabel('Altura (m)');
1126                 title(fig_title);
1127
1128                 % Realiza los analisis por modo
1129                 CBLegend = cell(1, 1+lenvmodo);
1130                 CBplotModoAnt = false;
1131                 CBLegend{1} = 'Envolvente';
1132                 phiac = analisisObj.phin' * acel;
1133                 for i = 1:lenvmodo
1134                     [~, ~, CBplotModo, ~, ~] = analisisObj.calcularMomentoCorteBasalAcel(analisisObj.phin(:, envmodo(i))*phiac(envmodo(i), :));
1135                     if i > 1
1136                         CBplotModo = CBplotModo + CBplotModoAnt;
1137                     end
1138                     CBplotModoAnt = CBplotModo;
1139                     plot(CBplotModo, hplot, '-', 'LineWidth', 1);
1140                     CBLegend{i+1} = sprintf('Modo %d', envmodo(i));
1141                 end % for i
1142                 if lenvmodo > 0
1143                     legend(CBLegend);
1144                 end
1145                 dplot = true;
1146             end
1147
1148             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'envmomento')
1149                 fig_title = sprintf('Envolvente de Momento Basal - %s %s', ctitle, carga.obtenerEtiqueta());
1150                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1151                 movegui(plt, 'center');
1152                 plot(MBplot, hplot, '*-', 'LineWidth', 1, 'Color', 'black');
1153                 grid on;
1154                 grid minor;
1155                 xlabel(sprintf('Momento (%s)', r.unidadM));
1156                 ylabel('Altura (m)');
1157                 title(fig_title);
1158                 dplot = true;
1159             end
1160
1161             % Si no se realizo ningun grafico
1162             if ~dplot
1163                 error('Tipo de grafico %s incorrecto, valores aceptados: %s', tipoplot, ...
1164                     'corte, momento, envcorte, envmomento');
1165             end
1166
1167             % Finaliza proceso
1168             drawnow();
1169             fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
1170             dispMetodoTEFAME();
1171
1172         end % calcularMomentoCorteBasal function
1173
1174         function calcularCurvasEnergia(analisisObj, carga, varargin)
1175             % calcularCurvasEnergia: Genera las curvas de energia a partir
1176             % de una carga
1177             %
1178             % calcularCurvasEnergia(analisisObj,carga,varargin)
1179             %
1180             % Parametros opcionales:
1181             %   'carga'         Booleano que indica si se grafica la carga o no
1182             %   'closeall'      Cierra todos los graficos
1183             %   'linewidth'     Ancho de linea de los graficos
1184             %   'mfilt'         Porcentaje de filtrado por numero de datos
1185             %   'norm1'         Normaliza con respecto al primer valor
1186             %   'plot'          'all','ek','ev','ekev','ebe','et','ed'
1187
1188             % Inicia el proceso
1189             tinicial = cputime;
1190
1191             % Recorre parametros opcionales
1192             p = inputParser;
1193             p.KeepUnmatched = true;
1194             addOptional(p, 'closeall', false);
1195             addOptional(p, 'linewidth', 1.2);
1196             addOptional(p, 'mfilt', 0.005);
1197             addOptional(p, 'norm1', false);
1198             addOptional(p, 'plot', 'all');
1199             addOptional(p, 'plotcarga', false);
1200             parse(p, varargin{:});
1201             r = p.Results;
1202
1203             if r.closeall
1204                 close all;
1205             end
1206
1207             % Obtiene variables
1208             tipoplot = r.plot;
1209             plotcarga = r.plotcarga;
1210
1211             % Verifica que la carga se haya calculado
1212             if ~(isa(carga, 'CargaDinamica') || isa(carga, 'CombinacionCargas'))
1213                 error('Solo se pueden graficar cargas dinamicas o una combinacion de cargas');
1214             end
1215             c_u = carga.obtenerDesplazamiento();
1216             c_v = carga.obtenerVelocidad();
1217             c_p = carga.obtenerCarga();
1218
1219             if ~carga.cargaCalculada()
1220                 error('La carga %s no se ha calculado', carga.obtenerEtiqueta());
1221             end
1222
1223             % Realiza calculos de energia
1224             fprintf('Calculando curvas de energia:\n');
1225             ctitle = analisisObj.imprimirPropiedadesAnalisisCarga(carga);
1226
1227             % Obtiene las matrices
1228             k = analisisObj.obtenerMatrizRigidez();
1229             m = analisisObj.obtenerMatrizMasa();
1230             c = analisisObj.obtenerMatrizAmortiguamiento(carga.usoAmortiguamientoRayleigh());
1231
1232             % Si se usaron disipadores
1233             if carga.usoDeDisipadores()
1234                 cdv = analisisObj.obtenerMatrizAmortiguamientoDisipadores();
1235                 kdv = analisisObj.obtenerMatrizRigidezDisipadores();
1236                 fprintf('\t\tLa %s se calculo con disipadores\n', lower(ctitle));
1237             else
1238                 fprintf('\t\tLa %s se calculo sin disipadores\n', lower(ctitle));
1239             end
1240
1241             % Graficos
1242             [~, s] = size(c_u);
1243             t = carga.obtenerVectorTiempo(); % Vector de tiempo
1244
1245             % Energia cinetica
1246             e_k = zeros(1, s);
1247             ek1 = 0;
1248             fprintf('\tCalculando energia cinetica\n');
1249             for i = 1:s
1250                 vv = c_v(:, i); % Obtiene el vector de velocidad para el tiempo i
1251                 e_k(i) = 0.5 * vv' * m * vv;
1252                 if i == 1
1253                     ek1 = e_k(i);
1254                 end
1255                 if r.norm1
1256                     e_k(i) = e_k(i) - ek1;
1257                 end
1258             end % for i
1259
1260             % Energia elastica
1261             e_v = zeros(1, s);
1262             fprintf('\tCalculando energia elastica\n');
1263             ev1 = 0;
1264             for i = 1:s
1265                 vv = c_u(:, i); % Obtiene el vector de desplazamiento para el tiempo i
1266                 e_v(i) = 0.5 * vv' * k * vv;
1267                 if i == 1
1268                     ev1 = e_v(1);
1269                 end
1270                 if r.norm1
1271                     e_v(i) = e_v(i) - ev1; % Normaliza restando el valor inicial
1272                 end
1273             end % for i
1274
1275             % Energia elastica disipadores
1276             e_vamori = zeros(1, s); % Parcial
1277             e_vamor = zeros(1, s); % Integral
1278             ev1a = 0;
1279
1280             if carga.usoDeDisipadores()
1281                 fprintf('\tCalculando energia elastica de los amortiguadores\n');
1282                 for i = 1:s
1283                     uu = c_u(:, i); % Obtiene el vector de desplazamiento para el tiempo i
1284                     e_vamori(i) = uu' * kdv * uu;
1285                     if i == 1
1286                         ev1a = e_vamori(1);
1287                     end
1288                     if r.norm1 % Normaliza con el primer valor
1289                         e_vamori(i) = e_vamori(i) - ev1a;
1290                     end
1291                     if i > 1
1292                         dt = t(i) - t(i - 1);
1293                         e_vamor(i) = e_vamor(i - 1) + 0.5 * (e_vamori(i) + e_vamori(i - 1)) * dt;
1294                     end
1295                 end % for i
1296             end
1297
1298             % Energia disipada
1299             e_di = zeros(1, s); % Parcial
1300             e_d = zeros(1, s); % Integral
1301             ed1 = 0;
1302
1303             fprintf('\tCalculando energia disipada por la estructura\n');
1304             for i = 1:s
1305                 vv = c_v(:, i); % Obtiene el vector de velocidad para el tiempo i
1306                 e_di(i) = vv' * c * vv;
1307                 if i == 1
1308                     ed1 = e_di(1);
1309                 end
1310                 if r.norm1 % Normaliza con el primer valor
1311                     e_di(i) = e_di(i) - ed1;
1312                 end
1313                 if i > 1
1314                     dt = t(i) - t(i-1);
1315                     e_d(i) = e_d(i-1) + 0.5 * (e_di(i) + e_di(i-1)) * dt;
1316                 end
1317             end % for i
1318
1319             % Energia disipada amortiguadores
1320             e_damori = zeros(1, s); % Parcial
1321             e_damor = zeros(1, s); % Integral
1322             eda1 = 0;
1323
1324             if carga.usoDeDisipadores()
1325                 fprintf('\tCalculando energia disipada por los amortiguadores\n');
1326                 for i = 1:s
1327                     vv = c_v(:, i); % Obtiene el vector de velocidad para el tiempo i
1328                     e_damori(i) = vv' * cdv * vv;
1329                     if i == 1
1330                         eda1 = e_damori(1);
1331                     end
1332                     if r.norm1 % Normaliza con el primer valor
1333                         e_damori(i) = e_damori(i) - eda1;
1334                     end
1335                     if i > 1
1336                         dt = t(i) - t(i - 1);
1337                         e_damor(i) = e_damor(i - 1) + 0.5 * (e_damori(i) + e_damori(i - 1)) * dt;
1338                     end
1339                 end % for i
1340             end
1341
1342             % Trabajo externo
1343             w_ei = zeros(1, s); % Parcial
1344             w_e = zeros(1, s); % Integral
1345             fprintf('\tCalculando trabajo externo\n');
1346             for i = 1:s
1347                 w_ei(i) = c_p(:, i)' * c_v(:, i);
1348                 if i > 1
1349                     dt = t(i) - t(i-1);
1350                     w_e(i) = w_e(i-1) + 0.5 * (w_ei(i) + w_ei(i-1)) * dt;
1351                 end
1352             end % for i
1353
1354             % Energia total
1355             e_t = zeros(1, s);
1356             fprintf('\tCalculando energia total\n');
1357             for i = 1:s
1358                 e_t(i) = e_k(1) + (e_v(1) + e_vamor(1)) + w_e(i) - (e_d(i) + e_damor(i));
1359             end % for i
1360
1361             % Balance energetico normalizado
1362             ebe = zeros(1, s);
1363             fprintf('\tCalculando balance energetico\n');
1364             for i = 1:s
1365                 ebe(i) = abs(w_e(i)-e_k(i)-(e_d(i) + e_damor(i))) / abs(w_e(i)) * 100;
1366             end % for i
1367
1368             % Graficos
1369             fprintf('\tGenerando graficos\n');
1370             lw = r.linewidth; % Linewidth de los graficos
1371             dplot = false; % Indica que un grafico se realizo
1372
1373             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'ek')
1374                 fig_title = sprintf('E_K Energia Cinetica - %s %s', ctitle, carga.obtenerEtiqueta());
1375                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1376                 movegui(plt, 'center');
1377                 plot(t, e_k, '-', 'LineWidth', lw);
1378                 grid on;
1379                 grid minor;
1380                 xlabel('Tiempo (s)');
1381                 ylabel('Energia cinetica');
1382                 title(fig_title);
1383                 ylims = get(gca, 'YLim');
1384                 ylim([0, max(ylims)]);
1385                 if plotcarga % Grafica la carga
1386                     axes('Position', [.59, .70, .29, .20]);
1387                     box on;
1388                     plot(t, c_p, 'k-', 'Linewidth', 0.8);
1389                     grid on;
1390                 end
1391                 dplot = true;
1392             end
1393
1394             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'ev')
1395                 fig_title = sprintf('E_V Energia Elastica - %s %s', ...
1396                     ctitle, carga.obtenerEtiqueta());
1397                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1398                 movegui(plt, 'center');
1399                 plot(t, e_v+e_vamor, '-', 'LineWidth', lw);
1400                 grid on;
1401                 grid minor;
1402                 xlabel('Tiempo (s)');
1403                 ylabel('Energia elastica');
1404                 title(fig_title);
1405                 ylims = get(gca, 'YLim');
1406                 ylim([0, max(ylims)]);
1407                 if plotcarga % Grafica la carga
1408                     axes('Position', [.59, .70, .29, .20]);
1409                     box on;
1410                     plot(t, c_p, 'k-', 'Linewidth', 0.8);
1411                     grid on;
1412                 end
1413                 dplot = true;
1414             end
1415
1416             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'ebe')
1417                 fig_title = sprintf('Balance Energetico Normalizado - %s %s', ...
1418                     ctitle, carga.obtenerEtiqueta());
1419                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1420                 movegui(plt, 'center');
1421                 plot(t, ebe, '-', 'LineWidth', lw);
1422                 grid on;
1423                 grid minor;
1424                 xlabel('Tiempo (s)');
1425                 ylabel('EBE (%)');
1426                 title(fig_title);
1427                 ylims = get(gca, 'YLim');
1428                 ylim([0, max(ylims)]);
1429                 if plotcarga % Grafica la carga
1430                     axes('Position', [.59, .70, .29, .20]);
1431                     box on;
1432                     plot(t, c_p, 'k-', 'Linewidth', 0.8);
1433                     grid on;
1434                 end
1435                 dplot = true;
1436             end
1437
1438             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'evek') || strcmp(tipoplot, 'ekev')
1439                 fig_title = sprintf('Energia Potencial - Cinetica - %s %s', ...
1440                     ctitle, carga.obtenerEtiqueta());
1441                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1442                 movegui(plt, 'center');
1443                 plot(t, e_k, '-', 'LineWidth', lw);
1444                 hold on;
1445                 plot(t, e_v+e_vamor, '-', 'LineWidth', lw);
1446                 grid on;
1447                 grid minor;
1448                 xlabel('Tiempo (s)');
1449                 ylabel('Energia');
1450                 legend({'E_K Energia cinetica', 'E_V Energia elastica'}, ...
1451                     'location', 'northeast');
1452                 title(fig_title);
1453                 ylims = get(gca, 'YLim');
1454                 ylim([0, max(ylims)]);
1455                 if plotcarga % Grafica la carga
1456                     axes('Position', [.59, .55, .29, .20]);
1457                     box on;
1458                     plot(t, c_p, 'k-', 'Linewidth', 0.8);
1459                     grid on;
1460                 end
1461                 dplot = true;
1462             end
1463
1464             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'et')
1465                 fig_title = sprintf('Energia Total - Disipada - Ingresada - %s %s', ...
1466                     ctitle, carga.obtenerEtiqueta());
1467                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1468                 movegui(plt, 'center');
1469                 plot(t, e_t, '-', 'LineWidth', lw);
1470                 hold on;
1471                 plot(t, e_d+e_damor, '-', 'LineWidth', lw);
1472                 plot(t, w_e, '-', 'LineWidth', lw);
1473                 grid on;
1474                 grid minor;
1475                 xlabel('Tiempo (s)');
1476                 ylabel('Energia');
1477                 legend({'E_t Energia total', 'E_D Energia disipada total', ...
1478                     'W_E Trabajo externo'}, 'location', 'southeast');
1479                 title(fig_title);
1480                 ylims = get(gca, 'YLim');
1481                 ylim([0, max(ylims)]);
1482                 if plotcarga % Grafica la carga
1483                     axes('Position', [.59, .36, .29, .20]);
1484                     box on;
1485                     plot(t, c_p, 'k-', 'Linewidth', 0.8);
1486                     grid on;
1487                 end
1488                 dplot = true;
1489             end
1490
1491             if strcmp(tipoplot, 'all') || strcmp(tipoplot, 'ed')
1492
1493                 % Graficos energia disipada
1494                 fig_title = sprintf('Energia Disipada - %s %s', ...
1495                     ctitle, carga.obtenerEtiqueta());
1496                 plt = figure('Name', fig_title, 'NumberTitle', 'off');
1497                 movegui(plt, 'center');
1498                 if carga.usoDeDisipadores()
1499                     plot(t, e_d+e_damor, '-', 'LineWidth', lw);
1500                     hold on;
1501                     plot(t, e_d, '-', 'LineWidth', lw);
1502                     plot(t, e_damor, '-', 'LineWidth', lw);
1503                     legend({'Energia disipada total', 'Energia disipada por la estructura', ...
1504                         'Energia disipada por disipadores'}, 'location', 'Best');
1505                 else
1506                     plot(t, e_d, '-', 'LineWidth', lw);
1507                     % legend({'Energia disipada por la estructura'}, 'location', 'Best');
1508                 end
1509                 grid on;
1510                 grid minor;
1511                 xlabel('Tiempo (s)');
1512                 ylabel('Energia');
1513                 title(fig_title);
1514                 ylims = get(gca, 'YLim');
1515                 ylim([0, max(ylims)]);
1516                 % if plotcarga % Grafica la carga
1517                 %     axes('Position', [.59, .36, .29, .20]);
1518                 %     box on;
1519                 %     plot(t, c_p, 'k-', 'Linewidth', 0.8);
1520                 %     grid on;
1521                 % end
1522                 dplot = true;
1523
1524                 % Comparacion energia estructura y disipador
1525                 if carga.usoDeDisipadores()
1526                     fig_title = {'Razon energia estructura - disipador', ...
1527                         sprintf('%s %s', ctitle, carga.obtenerEtiqueta())};
1528                     plt = figure('Name', fig_title{1}, 'NumberTitle', 'off');
1529                     movegui(plt, 'center');
1530                     plot(t, medfilt1(e_d./e_damor, floor(r.mfilt*length(e_d))), ...
1531                         '-', 'LineWidth', lw);
1532                     grid on;
1533                     grid minor;
1534                     xlabel('Tiempo (s)');
1535                     ylabel('Razon estructura/disipador');
1536                     title(fig_title);
1537                     ylims = get(gca, 'YLim');
1538                     ylim([0, max(ylims)]);
1539                     if plotcarga % Grafica la carga
1540                         axes('Position', [.59, .68, .29, .20]);
1541                         box on;
1542                         plot(t, c_p, 'k-', 'Linewidth', 0.8);
1543                         grid on;
1544                     end
1545                 end
1546
1547             end
1548
1549             % Si no se realizo ningun grafico
1550             if ~dplot
1551                 error('Tipo de grafico %s incorrecto, valores aceptados: %s', tipoplot, ...
1552                     'ek, ev, ekev, ebe, et, ed');
1553             end
1554
1555             % Finaliza proceso
1556             drawnow();
1557             fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
1558             dispMetodoTEFAME();
1559
1560         end % calcularCurvasEnergia function
1561
1562         function e_v = calcularModosEnergia(analisisObj, carga, dispinfo)
1563             % calcularModosEnergia: Metodo que calcula las energias
1564             % elasticas asociadas a una carga por cada modo y retorna una
1565             % matriz ordenada por energia y numero de modos
1566             %
1567             % w = calcularModosEnergia(analisisObj,carga,dispinfo)
1568
1569             if ~exist('dispinfo', 'var')
1570                 dispinfo = true;
1571             end
1572
1573             % Verifica que la carga se haya calculado
1574             if ~isa(carga, 'CargaDinamica')
1575                 error('Solo se pueden graficar cargas dinamicas');
1576             end
1577             c_u = carga.obtenerDesplazamiento();
1578
1579             % No usar carga.cargaCalculada() dado que este metodo es usado
1580             % por Newmark al iterar sobre los disipadores
1581             if isempty(c_u)
1582                 error('La carga %s no se ha calculado', carga.obtenerEtiqueta());
1583             end
1584
1585             if dispinfo
1586                 fprintf('\tCalculando energia elastica por cada modo:\n');
1587                 analisisObj.imprimirPropiedadesAnalisisCarga(carga);
1588             end
1589
1590             % Obtiene las matrices
1591             k = analisisObj.obtenerMatrizRigidez();
1592             phi = analisisObj.obtenerMatrizPhi();
1593
1594             % Realiza calculos de energia elastica
1595             [~, s] = size(c_u);
1596
1597             % Energia elastica total
1598             e_v = zeros(analisisObj.numModos, 5);
1599             for j = 1:analisisObj.numModos % Recorre cada modo
1600                 e_vsum = 0; % Suma la energia asociada a un modo para todo el tiempo
1601                 kj = phi(:, j)' * k;
1602                 for i = 1:s % Recorre el tiempo
1603                     vv = c_u(:, i); % Obtiene el vector de desplazamiento para el tiempo i
1604                     e_vsum = e_vsum + 0.5 * vv' * phi(:, j) * kj * vv;
1605                 end % for i
1606                 e_v(j, 1) = j;
1607                 e_v(j, 2) = analisisObj.wn(j);
1608                 e_v(j, 3) = 2 * pi() / analisisObj.wn(j);
1609                 e_v(j, 4) = abs(e_vsum);
1610             end % for j
1611
1612             % Normaliza por el maximo
1613             e_vmax = max(e_v(:, 4));
1614             for j = 1:analisisObj.numModos
1615                 e_v(j, 4) = e_v(j, 4) / e_vmax;
1616             end % for j
1617
1618             % Suma
1619             e_vsum = sum(e_v(:, 4));
1620             for j = 1:analisisObj.numModos
1621                 e_v(j, 5) = e_v(j, 4) / e_vsum;
1622             end % for j
1623
1624             % Ordena la matriz
1625             e_v = sortrows(e_v, -4);
1626
1627         end % calcularModosEnergia function
1628
1629         function [esfmax, esf, maxp, dirk] = calcularEsfuerzosElemento(analisisObj, carga, elemento, direccion)
1630             % calcularEsfuerzosElemento: Calcula los esfuerzos maximos de
1631             % un elemento a partir de una carga dinamica
1632             %
1633             % [esfmax,esf,maxp,dirk] = calcularEsfuerzosElemento(analisisObj,carga,elemento,direccion)
1634
1635             % Obtiene resultados de la carga
1636             u_c = carga.obtenerDesplazamiento();
1637
1638             % Verifica que la carga se haya calculado
1639             if ~(isa(carga, 'CargaDinamica') || isa(carga, 'CombinacionCargas'))
1640                 error('Solo se pueden graficar cargas dinamicas o combinaciones de cargas');
1641             end
1642             if ~carga.cargaCalculada()
1643                 error('La carga %s no se ha calculado', carga.obtenerEtiqueta());
1644             end
1645
1646             % Verifica que el elemento este bien definido
1647             if ~isa(elemento, 'Elemento')
1648                 error('El elemento no pertenece a la clase Elemento');
1649             end
1650
1651             % Genera el esfuerzo por el tiempo
1652             t = carga.obtenerVectorTiempo(); % Vector de tiempo
1653             esf = zeros(analisisObj.modeloObj.obtenerNumerosGDL(), length(t));
1654             esfmax = zeros(analisisObj.modeloObj.obtenerNumerosGDL(), 1);
1655
1656             % Obtiene desplazamientos originales de los nodos del elemento
1657             nodos = elemento.obtenerNodos();
1658             despl = {};
1659             for i = 1:length(nodos)
1660                 despl{i} = nodos{i}.obtenerDesplazamientos(); %#ok<AGROW>
1661             end
1662             ngdl = nodos{1}.obtenerNumeroGDL();
1663
1664             % Verifica la direccion
1665             dirk = 1; % Direccion de analisis de cada elemento
1666             if direccion ~= 0
1667                 if ~(verificarVectorDireccion(direccion, nodos{1}.obtenerNumeroGDL())) || sum(direccion) ~= 1
1668                     error('Direccion de analisis del elemento mal definido');
1669                 end
1670                 for i = 1:length(direccion)
1671                     if direccion(i) == 1
1672                         dirk = i;
1673                         break;
1674                     end
1675                 end % for i
1676             end
1677
1678             % Posicion del maximo
1679             maxp = 1;
1680             maxv = 0;
1681
1682             % Por cada tiempo obtiene la fuerza resistente local
1683             for i = 1:length(t)
1684
1685                 % Define los desplazamientos del nodo
1686                 for j = 1:length(nodos)
1687                     k = nodos{j}.obtenerGDLIDCondensado();
1688                     unodo = zeros(1, ngdl);
1689                     for n = 1:ngdl % Recorre cada desplazamiento de ese grado para el tiempo i
1690                         if k(n) > 0
1691                             unodo(n) = u_c(k(n), i);
1692                         end
1693                     end % for n
1694                     nodos{j}.definirDesplazamientos(unodo);
1695                 end % for j
1696
1697                 % Obtiene la fuerza resistente
1698                 fr = elemento.obtenerFuerzaResistenteCoordLocal();
1699                 for j = 1:length(fr) / 2
1700                     esf(j, i) = fr(j);
1701                 end % for j
1702
1703                 % Actualiza el maximo
1704                 if abs(esf(dirk, i)) > maxv
1705                     maxv = abs(esf(dirk, i));
1706                     maxp = i;
1707                 end
1708
1709                 for j = 1:length(esfmax)
1710                     if abs(esf(j, i)) > abs(esfmax(j))
1711                         esfmax(j) = esf(j, i);
1712                     end
1713                 end % for j
1714
1715             end % for i
1716
1717             % Resetea los desplazamientos originales
1718             for i = 1:length(nodos)
1719                 nodos{i}.definirDesplazamientos(despl{i});
1720             end % for i
1721
1722         end % calcularEsfuerzosElemento function
1723
1724         function plotEsfuerzosElemento(analisisObj, carga, elemento, direccion, varargin)
1725             % plotEsfuerzosElemento: Grafica los esfuerzos de un elemento
1726             %
1727             % plotEsfuerzosElemento(analisisObj,carga,elemento,direccion,varargin)
1728             %
1729             % Parametros opcionales:
1730             %   'tlim'      Tiempo de analisis limite
1731             %   'unidadC'   Unidad corte
1732             %   'unidadM'   Unidad momento
1733
1734             % Inicia el proceso
1735             tinicial = cputime;
1736
1737             % Recorre parametros opcionales
1738             p = inputParser;
1739             p.KeepUnmatched = true;
1740             addOptional(p, 'tlim', 0);
1741             addOptional(p, 'unidadC', 'tonf');
1742             addOptional(p, 'unidadM', 'tonf-m');
1743             parse(p, varargin{:});
1744             r = p.Results;
1745
1746             % Obtiene las variables
1747             tlim = r.tlim;
1748
1749             % Verifica que el elemento este bien definido
1750             if ~isa(elemento, 'Elemento')
1751                 error('El elemento no pertenece a la clase Elemento');
1752             end
1753
1754             % Realiza calculos de esfuerzo
1755             fprintf('Calculando esfuerzos elemento:\n');
1756             fprintf('\tElemento %s\n', elemento.obtenerEtiqueta());
1757             ctitle = analisisObj.imprimirPropiedadesAnalisisCarga(carga);
1758             [~, esf, maxp, dirk] = analisisObj.calcularEsfuerzosElemento(carga, elemento, direccion);
1759
1760             % Genera el vector de tiempo
1761             t = carga.obtenerVectorTiempo(); % Vector de tiempo
1762             if tlim == 0
1763                 tlim = [min(t), max(t)];
1764             else
1765                 tlim = [max(min(tlim), min(t)), min(max(tlim), max(t))];
1766             end
1767
1768             dirn = '';
1769             diru = '';
1770             if dirk == 1
1771                 dirn = 'Axial';
1772                 diru = r.unidadC;
1773             elseif dirk == 2
1774                 dirn = 'Corte';
1775                 diru = r.unidadC;
1776             elseif dirk == 3
1777                 dirn = 'Giro';
1778                 diru = r.unidadM;
1779             end
1780
1781             % Crea el grafico
1782             fig_title = sprintf('%s %s - Elemento %s - Direccion %s', ...
1783                 ctitle, carga.obtenerEtiqueta(), elemento.obtenerEtiqueta(), dirn);
1784             plt = figure('Name', fig_title, 'NumberTitle', 'off');
1785             movegui(plt, 'center');
1786
1787             plot(t, esf(dirk, :), '-', 'LineWidth', 1);
1788             ylabel(sprintf('Esfuerzo (%s)', diru));
1789             xlabel('t (s)');
1790             hold on;
1791
1792             % Grafica el maximo
1793             drawVyLine(esf(dirk, maxp), 'k--', 1.25);
1794             xlim(tlim);
1795             grid on;
1796             title(fig_title);
1797
1798             legend({sprintf('Esfuerzo elemento: %s', carga.obtenerEtiqueta()), ...
1799                 sprintf('Esfuerzo maximo: %.2f (%s)', esf(dirk, maxp), diru)}, ...
1800                 'location', 'southeast');
1801
1802             % Finaliza proceso
1803             fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
1804             dispMetodoTEFAME();
1805
1806         end % plotEsfuerzosElemento function
1807
1808         function plotTrayectoriaNodo(analisisObj, carga, nodo, direccion, varargin)
1809             % plotTrayectoriaNodo: Grafica la trayectoria de un nodo
1810             % (desplazamiento, velocidad y aceleracion) para todo el tiempo
1811             %
1812             % plotTrayectoriaNodo(analisisObj,carga,nodo,direccion,varargin)
1813             %
1814             % Parametros opcionales:
1815             %   'tlim'      Tiempo de analisis limite
1816             %   'unidadC'   Unidad carga
1817             %   'unidadL'   Unidad longitud
1818
1819             % Inicia proceso
1820             tinicial = cputime;
1821
1822             % Verifica que la direccion sea correcta
1823             if sum(direccion) ~= 1
1824                 error('Direccion invalida');
1825             end
1826             if ~verificarVectorDireccion(direccion, nodo.obtenerNumeroGDL())
1827                 error('Vector direccion mal definido');
1828             end
1829
1830             % Recorre parametros opcionales
1831             p = inputParser;
1832             p.KeepUnmatched = true;
1833             addOptional(p, 'tlim', 0);
1834             addOptional(p, 'unidadC', 'tonf');
1835             addOptional(p, 'unidadL', 'm');
1836             parse(p, varargin{:});
1837             r = p.Results;
1838
1839             % Obtiene las variables
1840             tlim = r.tlim;
1841
1842             % Obtiene resultados de la carga
1843             p_c = carga.obtenerCarga();
1844             u_c = carga.obtenerDesplazamiento();
1845             v_c = carga.obtenerVelocidad();
1846             a_c = carga.obtenerAceleracion();
1847
1848             % Verifica que la carga se haya calculado
1849             if ~(isa(carga, 'CargaDinamica') || isa(carga, 'CombinacionCargas'))
1850                 error('Solo se pueden graficar cargas dinamicas o combinaciones de cargas');
1851             end
1852             if ~carga.cargaCalculada()
1853                 error('La carga %s no se ha calculado', carga.obtenerEtiqueta());
1854             end
1855
1856             fprintf('Calculando trayectoria nodo:\n');
1857             fprintf('\tNodo %s\n', nodo.obtenerEtiqueta());
1858             ctitle = analisisObj.imprimirPropiedadesAnalisisCarga(carga);
1859
1860             % Elige al nodo
1861             [r, ~] = size(a_c);
1862             ngd = nodo.obtenerGDLIDCondensado();
1863             ng = 0; % Numero grado analisis
1864             nd = 0; % Numero direccion analisis
1865             for i = 1:length(direccion)
1866                 if direccion(i) == 1
1867                     ng = ngd(i);
1868                     nd = i;
1869                 end
1870             end % for i
1871             if ng == 0
1872                 error('No se ha obtenido el GDLID del nodo, es posible que corresponda a un apoyo o bien que el grado de libertad fue condensado');
1873             end
1874             if ng > r
1875                 error('El GDLID excede al soporte del sistema');
1876             end
1877
1878             % Genera el vector de tiempo
1879             t = carga.obtenerVectorTiempo(); % Vector de tiempo
1880             if tlim == 0
1881                 tlim = [min(t), max(t)];
1882             else
1883                 tlim = [max(min(tlim), min(t)), min(max(tlim), max(t))];
1884             end
1885
1886             % Crea el grafico
1887             fig_title = sprintf('%s %s - Nodo %s - GDLID condensado %d - Direccion %d', ...
1888                 ctitle, carga.obtenerEtiqueta(), nodo.obtenerEtiqueta(), ng, nd);
1889             plt = figure('Name', fig_title, 'NumberTitle', 'off');
1890             movegui(plt, 'center');
1891
1892             subplot(4, 1, 1);
1893             plot(t, p_c(ng, :), 'k-', 'LineWidth', 1);
1894             ylabel(sprintf('carga (%s)', r.unidadC));
1895             xlabel('t (s)');
1896             xlim(tlim);
1897             grid on;
1898             title(fig_title);
1899
1900             subplot(4, 1, 2);
1901             plot(t, u_c(ng, :), 'k-', 'LineWidth', 1);
1902             title('Desplazamiento');
1903             ylabel(sprintf('u (%s)', r.unidadL));
1904             xlabel('t (s)');
1905             xlim(tlim);
1906             grid on;
1907
1908             subplot(4, 1, 3);
1909             plot(t, v_c(ng, :), 'k-', 'LineWidth', 1);
1910             title('Velocidad');
1911             ylabel(sprintf('v (%s/s)', r.unidadL));
1912             xlabel('t (s)');
1913             xlim(tlim);
1914             grid on;
1915
1916             subplot(4, 1, 4);
1917             plot(t, a_c(ng, :), 'k-', 'LineWidth', 1);
1918             title('Aceleracion');
1919             ylabel(sprintf('a (%s/s^s)', r.unidadL));
1920             xlabel('t (s)');
1921             xlim(tlim);
1922             grid on;
1923
1924             % Finaliza proceso
1925             fprintf('\tProceso finalizado en %.2f segundos\n', cputime-tinicial);
1926             dispMetodoTEFAME();
1927
1928         end % plotTrayectoriaNodo function
1929
1930         function activarCargaAnimacion(analisisObj)
1931             % activarCargaAnimacion: Carga la animacion  una vez calculada
1932             %
1933             % activarCargaAnimacion(analisisObj)
1934
1935             analisisObj.cargarAnimacion = true;
1936
1937         end % activarCargaAnimacion funcion
1938
1939         function desactivarCargaAnimacion(analisisObj)
1940             % desactivarCargaAnimacion: Desactiva la animacion una vez calculada
1941             %
1942             % desactivarCargaAnimacion(analisisObj)
1943
1944             analisisObj.cargarAnimacion = false;
1945
1946         end % desactivarCargaAnimacion funcion
1947
1948         function activarPlotDeformadaInicial(analisisObj)
1949             % activarPlotDeformadaInicial: Activa el grafico de la deformada inicial
1950             %
1951             % activarPlotDeformadaInicial(analisisObj)
1952
1953             analisisObj.mostrarDeformada = true;
1954
1955         end % activarPlotDeformadaInicial function
1956
1957         function desactivarPlotDeformadaInicial(analisisObj)
1958             % desactivarPlotDeformadaInicial: Desactiva el grafico de la deformada inicial
1959             %
1960             % desactivarPlotDeformadaInicial(analisisObj)
1961
1962             analisisObj.mostrarDeformada = false;
1963
1964         end % desactivarPlotDeformadaInicial function
1965
1966         function disp(analisisObj)
1967             % disp: es un metodo de la clase ModalEspectral que se usa para imprimir en
1968             % command Window la informacion del analisis espectral realizado
1969             %
1970             % disp(analisisObj)
1971             %
1972             % Imprime la informacion guardada en el ModalEspectral (analisisObj) en
1973             % pantalla
1974
1975             if ~analisisObj.analisisFinalizado
1976                 error('El analisis modal aun no ha sido calculado');
1977             end
1978
1979             fprintf('Propiedades analisis modal espectral:\n');
1980
1981             % Muestra los grados de libertad
1982             fprintf('\tNumero de grados de libertad: %d\n', ...
1983                 analisisObj.numeroGDL-analisisObj.gdlCond);
1984             fprintf('\tNumero de grados condensados: %d\n', analisisObj.gdlCond);
1985             fprintf('\tNumero de direcciones por grado: %d\n', analisisObj.numDG);
1986             fprintf('\tNumero de modos en el analisis: %d\n', analisisObj.numModos);
1987
1988             % Propiedades de las matrices
1989             detKt = det(analisisObj.Kt);
1990             detMt = det(analisisObj.Mt);
1991             if detKt ~= Inf
1992                 fprintf('\tMatriz de rigidez:\n');
1993                 fprintf('\t\tDeterminante: %f\n', detKt);
1994             end
1995             if abs(detMt) >= 1e-20
1996                 fprintf('\tMatriz de Masa:\n');
1997                 fprintf('\t\tDeterminante: %f\n', detMt);
1998             end
1999             fprintf('\tMasa total de la estructura: %.3f\n', analisisObj.Mtotal);
2000
2001             fprintf('\tPeriodos y participacion modal:\n');
2002             if analisisObj.numDG == 2
2003                 fprintf('\t\tN\t|\tT (s)\t| w (rad/s)\t|\tU1\t\t|\tU2\t\t|\tSum U1\t|\tSum U2\t|\n');
2004                 fprintf('\t\t-----------------------------------------------------------------------------\n');
2005             elseif analisisObj.numDG == 3
2006                 fprintf('\t\tN\t|\tT (s)\t| w (rad/s)\t|\tU1\t\t|\tU2\t\t|\tU3\t\t|\tSum U1\t|\tSum U2\t|\tSum U3\t|\n');
2007                 fprintf('\t\t----------------------------------------------------------------------------------------------------\n');
2008             end
2009
2010             for i = 1:analisisObj.numModos
2011                 if analisisObj.numDG == 2
2012                     fprintf('\t\t%d\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\n', i, analisisObj.Tn(i), ...
2013                         analisisObj.wn(i), analisisObj.Mmeff(i, 1), analisisObj.Mmeff(i, 2), ...
2014                         analisisObj.Mmeffacum(i, 1), analisisObj.Mmeffacum(i, 2));
2015                 elseif analisisObj.numDG == 3
2016                     fprintf('\t\t%d\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\t|\t%.3f\n', i, analisisObj.Tn(i), ...
2017                         analisisObj.wn(i), analisisObj.Mmeff(i, 1), analisisObj.Mmeff(i, 2), analisisObj.Mmeff(i, 3), ...
2018                         analisisObj.Mmeffacum(i, 1), analisisObj.Mmeffacum(i, 2), analisisObj.Mmeffacum(i, 3));
2019                 end
2020                 fprintf('\n');
2021             end % for i
2022
2023             % Busca los periodos para los cuales se logra el 90%
2024             mt90p = zeros(analisisObj.numDG, 1);
2025             for i = 1:analisisObj.numDG
2026                 fprintf('\t\tN periodo en U%d para el 90%% de la masa: ', i);
2027                 for j = 1:analisisObj.numModos
2028                     if analisisObj.Mmeffacum(j, i) >= 0.90
2029                         mt90p(i) = j;
2030                         break;
2031                     end
2032                 end % for j
2033                 if mt90p(i) > 0
2034                     fprintf('%d\n', mt90p(i));
2035                 else
2036                     fprintf('Incrementar modos de analisis\n');
2037                 end
2038             end % for i
2039
2040             dispMetodoTEFAME();
2041
2042         end % disp function
2043
2044         function c = obtenerCargaEstatica(analisisObj, varargin)
2045             % obtenerCargaEstatica: Obtiene la carga estatica del modelo
2046             % como una carga dinamica para ser incluida en las
2047             % combinaciones de cargas
2048             %
2049             % c = obtenerCargaEstatica(analisisObj,varargin)
2050             %
2051             % Parametros opcionales:
2052             %   'etiqueta'      Nombre de la carga
2053
2054             % Recorre parametros opcionales
2055             p = inputParser;
2056             p.KeepUnmatched = true;
2057             addOptional(p, 'etiqueta', 'Carga Estatica');
2058             parse(p, varargin{:});
2059             r = p.Results;
2060
2061             c = CargaDinamica(r.etiqueta);
2062             c.dt = 1;
2063             c.tAnalisis = 1;
2064
2065             % Crea vector de velocidad y aceleracion ceros
2066             v = zeros(length(analisisObj.u), 1);
2067             a = zeros(length(analisisObj.u), 1);
2068
2069             c.guardarCarga(analisisObj.F);
2070             c.guardarDesplazamiento(analisisObj.u);
2071             c.guardarVelocidad(v);
2072             c.guardarAceleracion(a);
2073
2074         end % obtenerCargaEstatica function
2075
2076     end % methods(public) ModalEspectral
2077
2078     methods(Access = private)
2079
2080         function definirNumeracionGDL(analisisObj)
2081             % definirNumeracionGDL: es un metodo de la clase ModalEspectral que
2082             % se usa para definir como se enumeran los GDL en el modelo
2083             %
2084             % definirNumeracionGDL(analisisObj)
2085             %
2086             % Define y asigna la enumeracion de los GDL en el modelo
2087
2088             fprintf('\tDefiniendo numeracion GDL\n');
2089
2090             % Primero se aplican las restricciones al modelo
2091             analisisObj.modeloObj.aplicarRestricciones();
2092
2093             % Extraemos los nodos para que sean enumerados
2094             nodoObjetos = analisisObj.modeloObj.obtenerNodos();
2095             numeroNodos = length(nodoObjetos);
2096
2097             % Inicializamos en cero el contador de GDL
2098             contadorGDL = 0;
2099             for i = 1:numeroNodos
2100
2101                 gdlidNodo = nodoObjetos{i}.obtenerGDLID;
2102
2103                 % Si no es reaccion entonces se agrega como GDL
2104                 for j = 1:length(gdlidNodo)
2105                     if (gdlidNodo(j) == -1)
2106                         contadorGDL = contadorGDL + 1;
2107                         gdlidNodo(j) = contadorGDL;
2108                     end % if
2109                 end % for j
2110                 nodoObjetos{i}.definirGDLID(gdlidNodo);
2111
2112             end % for i
2113
2114             % Guardamos el numero de GDL, es decir el numero de ecuaciones
2115             % del sistema
2116             analisisObj.numeroGDL = contadorGDL;
2117
2118             % Extraemos los Elementos del modelo
2119             elementoObjetos = analisisObj.modeloObj.obtenerElementos();
2120             disipadorObjetos = analisisObj.modeloObj.obtenerDisipadores();
2121             numeroElementos = length(elementoObjetos);
2122             numeroDisipadores = length(disipadorObjetos);
2123             % Definimos los GDLID en los elementos para poder formar la matriz de rigidez
2124             for i = 1:numeroElementos
2125                 elementoObjetos{i}.definirGDLID();
2126             end % for i
2127
2128             for i = 1:numeroDisipadores
2129                 disipadorObjetos{i}.definirGDLID();
2130             end % for i
2131
2132         end % definirNumeracionGDL function
2133
2134         function calcularModalEspectral(analisisObj, nModos, betacR, modocR, ...
2135                 direcR, betacP, maxcond, valvecAlgoritmo, valvecTolerancia, ...
2136                 muIterDesplazamiento)
2137             % calcularModalEspectral: Calcula el metodo modal espectral
2138             %
2139             % calcularModalEspectral(analisisObj,nModos,betacR,modocR,direcR,
2140             %   betacP,maxcond,valvecAlgoritmo,valvecTolerancia,muIterDesplazamiento)
2141
2142             % Calcula tiempo inicio
2143             fprintf('\tCalculando metodo modal espectral:\n');
2144             tInicio = cputime;
2145
2146             % Obtiene matriz de masa
2147             diagMt = diag(analisisObj.Mt);
2148             analisisObj.Mtotal = sum(diagMt) / 2;
2149
2150             % Obtiene los grados de libertad
2151             ngdl = length(analisisObj.Mt); % Numero de grados de libertad
2152             ndg = analisisObj.modeloObj.obtenerNumerosGDL(); % Grados de libertad por nodo
2153
2154             % ---------------- CONDENSACION ESTATICA DE GUYAN ---------------
2155             % Primero se genera matriz para reordenar elementos (rot)
2156             vz = []; % Vector que identifica indices a condensar
2157             j = 1;
2158             if maxcond >= 0
2159                 for i = 1:length(diagMt)
2160                     if diagMt(i) <= maxcond
2161                         vz(j) = i; %#ok<AGROW>
2162                         j = j + 1;
2163                     end
2164                 end % for i
2165             end
2166
2167             % Si condensa grados
2168             analisisObj.gdlCond = length(vz);
2169             realizaCond = false;
2170             if analisisObj.gdlCond > 0
2171
2172                 realizaCond = true;
2173                 % Chequea cuantos grados quedan
2174                 nndg = ndg;
2175                 if ndg > 2
2176                     for i = 2:ndg
2177                         % Si todos los grados se dividen por 3, entonces se borra
2178                         % el tercer grado de libertad (giro por ejemplo)
2179                         if allDivMod(vz, i)
2180                             nndg = nndg - 1;
2181                         end
2182                     end % for i
2183                 end
2184                 ndg = nndg;
2185
2186                 lpasivos = length(vz);
2187                 lactivos = length(diagMt) - lpasivos;
2188                 rot = zeros(length(diagMt), length(diagMt));
2189                 aux0 = 1;
2190                 aux1 = 1;
2191                 aux2 = length(diagMt) - lpasivos + 1;
2192                 for i = 1:1:length(rot)
2193                     if aux0 <= length(vz) && i == vz(aux0)
2194                         rot(i, aux2) = 1;
2195                         aux2 = aux2 + 1;
2196                         aux0 = aux0 + 1;
2197                     else
2198                         rot(i, aux1) = 1;
2199                         aux1 = aux1 + 1;
2200                     end
2201                 end % for i
2202
2203                 % Se realiza rotacion de matriz de rigidez
2204                 Krot = rot' * analisisObj.Kt * rot;
2205
2206                 % Se determina matriz de rigidez condensada (Keq)
2207                 Kaa = Krot(1:lactivos, 1:lactivos);
2208                 Kap = Krot(1:lactivos, lactivos+1:end);
2209                 Kpa = Krot(lactivos+1:end, 1:lactivos);
2210                 Kpp = Krot(lactivos+1:end, lactivos+1:end);
2211                 Keq = Kaa - Kap * Kpp^(-1) * Kpa;
2212
2213                 % Generacion de matriz T de condensacion
2214                 If = size(Kaa, 1);
2215                 T1 = eye(If);
2216                 T2 = -(Kpp)^(-1) * (Kpa);
2217                 T = vertcat(T1, T2);
2218
2219                 % Se determina matriz de masa condensada (Meq)
2220                 Mrot = rot' * analisisObj.Mt * rot;
2221                 Meq = T' * Mrot * T;
2222
2223                 % Condensa la fuerza estatica
2224                 analisisObj.F = rot' * analisisObj.F;
2225                 analisisObj.F = T' * analisisObj.F;
2226
2227                 % Condensa los desplazamientos estaticos
2228                 analisisObj.u = rot' * analisisObj.u;
2229                 analisisObj.u = T' * analisisObj.u;
2230
2231                 % Actualiza los grados
2232                 cngdl = length(Meq);
2233                 if cngdl < ngdl
2234                     fprintf('\t\tSe han condensado %d grados de libertad\n', ngdl-cngdl);
2235                     ngdl = cngdl;
2236                 end
2237
2238                 % Actualiza los nodos
2239                 nodos = analisisObj.modeloObj.obtenerNodos();
2240                 nnodos = length(nodos);
2241                 for i = 1:nnodos
2242                     gdl = nodos{i}.obtenerGDLID();
2243                     gdlaux = gdl;
2244                     for j = 1:length(gdl)
2245                         for k = 1:length(vz) % Recorre los grados condensados
2246                             if vz(k) == gdl(j)
2247                                 gdlaux(j) = 0; % gdl condensado
2248                             elseif vz(k) < gdl(j)
2249                                 gdlaux(j) = gdlaux(j) - 1;
2250                             else
2251                                 gdlaux(j) = gdlaux(j);
2252                             end
2253                         end % for k
2254                     end % for j
2255                     nodos{i}.definirGDLIDCondensado(gdlaux);
2256                 end % for i
2257
2258                 MtotalRed = sum(diag(Meq)) / 2;
2259                 fprintf('\t\tTras la condensacion la masa se redujo en %.2f (%.2f%%)\n', ...
2260                     analisisObj.Mtotal-MtotalRed, 100*(analisisObj.Mtotal - MtotalRed)/analisisObj.Mtotal);
2261
2262             else % No condensa grados
2263
2264                 Meq = analisisObj.Mt;
2265                 Keq = analisisObj.Kt;
2266                 fprintf('\t\tNo se han condensado grados de libertad\n');
2267
2268             end
2269
2270             % Una vez pasado este punto no deberian haber masas nulas o
2271             % incorrectas
2272             for i = 1:ngdl
2273                 if Meq(i, i) <= 0
2274                     error('La matriz de masa esta mal definida, M(%d,%d)<=0', i, i);
2275                 end
2276             end % for i
2277
2278             fprintf('\t\tGrados de libertad totales: %d\n', ngdl);
2279             fprintf('\t\tNumero de direcciones de analisis: %d\n', ndg);
2280             nModos = min(nModos, ngdl);
2281
2282             %------------- CALCULO VALORES Y VECTORES PROPIOS ---------------
2283             eigCalcT = cputime;
2284
2285             if strcmp(valvecAlgoritmo, 'eigs')
2286                 fprintf('\t\tCalculo valores y vectores propios con metodo eigs\n');
2287                 [modalPhin, modalWn] = calculoEigEigs(Meq, Keq, nModos);
2288             elseif strcmp(valvecAlgoritmo, 'itDir')
2289                 fprintf('\t\tCalculo valores y vectores con algoritmo iteracion directa\n');
2290                 fprintf('\t\t\tTolerancia: %.4f\n', valvecTolerancia);
2291                 [modalPhin, modalWn] = calculoEigIterDirecta(Meq, Keq, valvecTolerancia);
2292                 nModos = length(modalWn);
2293             elseif strcmp(valvecAlgoritmo, 'matBarr')
2294                 fprintf('\t\tCalculo valores y vectores propios con algoritmo matriz de barrido\n');
2295                 fprintf('\t\t\tTolerancia: %.4f\n', valvecTolerancia);
2296                 [modalPhin, modalWn] = calculoEigDirectaBarrido(Meq, Keq, nModos, valvecTolerancia);
2297             % elseif strcmp(valvecAlgoritmo, 'itInv')
2298             %     fprintf('\t\tCalculo valores y vectores propios con metodo iteracion inversa\n');
2299             elseif strcmp(valvecAlgoritmo, 'itInvDesp')
2300                 fprintf('\t\tCalculo valores y vectores propios con metodo iteracion inversa con desplazamientos\n');
2301                 fprintf('\t\t\tTolerancia: %.4f\n', valvecTolerancia);
2302                 fprintf('\t\t\tMu: %.4f\n', muIterDesplazamiento);
2303                 [modalPhin, modalWn] = calculoEigIterInvDesplazamiento(Meq, Keq, muIterDesplazamiento, valvecTolerancia);
2304                 nModos = length(modalWn);
2305             elseif strcmp(valvecAlgoritmo, 'itSubesp')
2306                 fprintf('\t\tCalculo valores y vectores propios con metodo iteracion del subespacio\n');
2307                 fprintf('\t\t\tTolerancia: %.4f\n', valvecTolerancia);
2308                 [modalPhin, modalWn] = calculoEigItSubespacio(Meq, Keq, nModos, valvecTolerancia);
2309             else
2310                 error('Algoritmo valvec:%s incorrecto, valores posibles: eigvc,itDir,matBarr,itInvDesp,itSubesp', ...
2311                     valvecAlgoritmo);
2312             end
2313             fprintf('\t\t\tFinalizado en %.3f segundos\n', cputime-eigCalcT);
2314             analisisObj.numModos = nModos;
2315
2316             % Se recuperan los grados de libertad condensados y se
2317             % ordenan de acuerdo a la configuracion original
2318             if realizaCond
2319                 modalPhinFull = T * modalPhin;
2320                 rot_inv = rot^(-1);
2321                 modalPhinFull = rot_inv' * modalPhinFull;
2322                 analisisObj.condMatT = T;
2323                 analisisObj.condMatRot = rot_inv;
2324             else
2325                 modalPhinFull = modalPhin;
2326                 analisisObj.condMatT = eye(length(modalPhin));
2327                 analisisObj.condMatRot = eye(length(modalPhin));
2328             end
2329
2330             % Calcula las frecuencias del sistema
2331             modalTn = (modalWn.^-1) .* 2 * pi(); % Calcula los periodos
2332
2333             % Calcula las matrices
2334             modalMmt = modalPhin' * Meq * modalPhin;
2335             modalPhin = modalPhin * diag(diag(modalMmt).^-0.5);
2336             modalMm = diag(diag(modalPhin'*Meq*modalPhin));
2337             modalKm = diag(diag(modalPhin'*Keq*modalPhin));
2338
2339             % Reordena los periodos
2340             Torder = zeros(nModos, 1);
2341             Tpos = 1;
2342             for i = 1:nModos
2343                 maxt = 0; % Periodo
2344                 maxi = 0; % Indice
2345                 for j = 1:nModos % Se busca el elemento para etiquetar
2346                     if Torder(j) == 0 % Si aun no se ha etiquetado
2347                         if modalTn(j) > maxt
2348                             maxt = modalTn(j);
2349                             maxi = j;
2350                         end
2351                     end
2352                 end % for j
2353                 Torder(maxi) = Tpos;
2354                 Tpos = Tpos + 1;
2355             end % for i
2356             % ngdl = length(Meq); % Numero de grados de libertad
2357
2358             % Asigna valores
2359             analisisObj.phinExt = modalPhinFull;
2360             analisisObj.Tn = zeros(nModos, 1);
2361             analisisObj.wn = zeros(nModos, 1);
2362             analisisObj.phin = zeros(ngdl, nModos);
2363             analisisObj.Mm = modalMm;
2364             analisisObj.Km = modalKm;
2365             analisisObj.Mteq = Meq;
2366             analisisObj.Kteq = Keq;
2367             for i = 1:nModos
2368                 analisisObj.Tn(Torder(i)) = modalTn(i);
2369                 analisisObj.wn(Torder(i)) = modalWn(i);
2370                 analisisObj.phin(:, Torder(i)) = modalPhin(:, i);
2371             end % for i
2372
2373             % Crea vector influencia
2374             analisisObj.rm = zeros(ngdl, ndg);
2375             for j = 1:ndg
2376                 for i = 1:ngdl
2377                     if mod(i, ndg) == j || (mod(i, ndg) == 0 && j == ndg)
2378                         analisisObj.rm(i, j) = 1;
2379                     end
2380                 end % for i
2381             end % for j
2382
2383             % Realiza el calculo de las participaciones modales
2384             analisisObj.Lm = zeros(nModos, ndg);
2385             analisisObj.Mmeff = zeros(ngdl, ndg);
2386             analisisObj.Mmeffacum = zeros(ngdl, ndg);
2387             Mtotr = zeros(ndg, 1);
2388
2389             % Recorre cada grado de libertad (horizontal, vertical, giro)
2390             for j = 1:ndg
2391                 Mtotr(j) = sum(Meq*analisisObj.rm(:, j));
2392                 for k = 1:nModos
2393                     analisisObj.Lm(k, j) = analisisObj.phin(:, k)' * Meq * analisisObj.rm(:, j);
2394                     analisisObj.Mmeff(k, j) = analisisObj.Lm(k, j).^2 ./ modalMm(k, k);
2395                 end % for k
2396
2397                 analisisObj.Mmeff(:, j) = analisisObj.Mmeff(:, j) ./ Mtotr(j);
2398                 analisisObj.Mmeffacum(1, j) = analisisObj.Mmeff(1, j);
2399                 for i = 2:nModos
2400                     analisisObj.Mmeffacum(i, j) = analisisObj.Mmeffacum(i-1, j) + analisisObj.Mmeff(i, j);
2401                 end % for i
2402             end % for j
2403
2404             % -------- CALCULO DE AMORTIGUAMIENTO DE RAYLEIGH -------------
2405
2406             % Se recorren los numero de modos, si alguno es mayor a los
2407             % modos de analisis se reajusta y lanza warning
2408             for i = 1:length(modocR)
2409                 if modocR(i) > nModos
2410                     warning('Modo de Rayleigh %d excede al numero de modos de analisis %d, se ha reajustado este ultimo', ...
2411                         modocR(i), nModos);
2412                     modocR(i) = nModos;
2413                 end
2414             end % for i
2415
2416             countcR = [0, 0];
2417             m = 0;
2418             n = 0;
2419             for i = 1:min(length(analisisObj.Mmeff), nModos)
2420                 if analisisObj.Mmeff(i, 1) > max(analisisObj.Mmeff(i, 2:ndg))
2421                     countcR(1) = countcR(1) + 1;
2422                     if direcR(1) == 'h' && modocR(1) == countcR(1)
2423                         m = i;
2424                     elseif direcR(2) == 'h' && modocR(2) == countcR(1)
2425                         n = i;
2426                     end
2427                 elseif analisisObj.Mmeff(i, 2) > ...
2428                         max(analisisObj.Mmeff(i, 1), analisisObj.Mmeff(i, max(1, ndg)))
2429                     countcR(2) = countcR(2) + 1;
2430                     if direcR(1) == 'v' && modocR(1) == countcR(2)
2431                         m = i;
2432                     elseif direcR(2) == 'h' && modocR(2) == countcR(2)
2433                         n = i;
2434                     end
2435                 end
2436             end % for i
2437
2438             if m == 0 || n == 0
2439                 warning('Se requiere aumentar el numero de modos para determinar matriz de amortiguamiento de Rayleigh');
2440                 m = 1;
2441                 n = 1;
2442             end
2443             w = analisisObj.wn;
2444             a = (2 * w(m) * w(n)) / (w(n)^2 - w(m)^2) .* [w(n), -w(m); ...
2445                 -1 / w(n), 1 / w(m)] * betacR';
2446             analisisObj.cRayleigh = a(1) .* Meq + a(2) .* Keq;
2447
2448             % ------ CALCULO DE AMORTIGUAMIENTO DE WILSON-PENZIEN ----------
2449             % Se declaran todos los amortiguamientos criticos del sistema,
2450             % (horizontal, vertical y rotacional)
2451             d = zeros(length(analisisObj.Mmeff), length(analisisObj.Mmeff));
2452             w = analisisObj.wn;
2453             Mn = modalMmt;
2454             analisisObj.cPenzien = 0;
2455
2456             for i = 1:length(Mn)
2457                 if analisisObj.Mmeff(i, 1) > max(analisisObj.Mmeff(i, 2:ndg))
2458                     d(i, i) = 2 * betacP(1) * w(i) / Mn(i, i);
2459                 elseif analisisObj.Mmeff(i, 2) > ...
2460                         max(analisisObj.Mmeff(i, 1), analisisObj.Mmeff(i, max(1, ndg)))
2461                     d(i, i) = 2 * betacP(2) * w(i) / Mn(i, i);
2462                 else
2463                     d(i, i) = 2 * betacP(3) * w(i) / Mn(i, i);
2464                 end
2465                 analisisObj.cPenzien = analisisObj.cPenzien + ...
2466                     Meq * (d(i, i) * modalPhin(:, i) * modalPhin(:, i)') * Meq;
2467             end % for i
2468
2469             % Termina el analisis
2470             analisisObj.analisisFinalizado = true;
2471             analisisObj.numDG = ndg;
2472             analisisObj.numDGReal = analisisObj.modeloObj.obtenerNumerosGDL();
2473             fprintf('\tSe completo el analisis en %.3f segundos\n', cputime-tInicio);
2474
2475         end % calcularModalEspectral function
2476
2477         function ensamblarMatrizRigidez(analisisObj)
2478             % ensamblarMatrizRigidez: es un metodo de la clase ModalEspectral que se usa para
2479             % realizar el armado de la matriz de rigidez del modelo analizado
2480             %
2481             % ensamblarMatrizRigidez(analisisObj)
2482             %
2483             % Ensambla la matriz de rigidez del modelo analizado usando el metodo
2484             % indicial
2485
2486             fprintf('\tEnsamblando matriz de rigidez\n');
2487             analisisObj.Kt = zeros(analisisObj.numeroGDL, analisisObj.numeroGDL);
2488
2489             % Extraemos los Elementos
2490             elementoObjetos = analisisObj.modeloObj.obtenerElementos();
2491             numeroElementos = length(elementoObjetos);
2492
2493             % Definimos los GDLID en los elementos
2494             for i = 1:numeroElementos
2495
2496                 % Se obienen los gdl del elemento metodo indicial
2497                 gdl = elementoObjetos{i}.obtenerGDLID();
2498                 ngdl = elementoObjetos{i}.obtenerNumeroGDL();
2499
2500                 % Se obtiene la matriz de rigidez global del elemento-i
2501                 k_globl_elem = elementoObjetos{i}.obtenerMatrizRigidezCoordGlobal();
2502
2503                 % Se calcula el metodo indicial
2504                 for r = 1:ngdl
2505                     for s = 1:ngdl
2506                         i_ = gdl(r);
2507                         j_ = gdl(s);
2508
2509                         % Si corresponden a grados de libertad -> puntos en (i,j)
2510                         % se suma contribucion metodo indicial
2511                         if (i_ ~= 0 && j_ ~= 0)
2512                             analisisObj.Kt(i_, j_) = analisisObj.Kt(i_, j_) + k_globl_elem(r, s);
2513                         end
2514
2515                     end % for s
2516                 end % for r
2517
2518             end % for i
2519
2520         end % ensamblarMatrizRigidez function
2521
2522         function ensamblarMatrizMasa(analisisObj)
2523             % ensamblarMatrizMasa: es un metodo de la clase ModalEspectral que se usa para
2524             % realizar el armado de la matriz de masa del modelo
2525             %
2526             % ensamblarMatrizMasa(analisisObj)
2527             %
2528             % Ensambla la matriz de masa del modelo analizado usando el metodo
2529             % indicial
2530
2531             fprintf('\tEnsamblando matriz de masa\n');
2532             analisisObj.Mt = zeros(analisisObj.numeroGDL, analisisObj.numeroGDL);
2533
2534             % Extraemos los Elementos
2535             fprintf('\t\tAgrega masa de elementos\n');
2536             elementoObjetos = analisisObj.modeloObj.obtenerElementos();
2537             numeroElementos = length(elementoObjetos);
2538
2539             % Definimos los GDLID en los elementos
2540             for i = 1:numeroElementos
2541
2542                 % Se obienen los gdl del elemento metodo indicial
2543                 gdl = elementoObjetos{i}.obtenerGDLID();
2544                 ngdl = elementoObjetos{i}.obtenerNumeroGDL();
2545
2546                 % Se obtiene la matriz de masa
2547                 m_elem = elementoObjetos{i}.obtenerVectorMasa();
2548
2549                 % Se calcula el metodo indicial
2550                 for r = 1:ngdl
2551                     for s = 1:ngdl
2552                         i_ = gdl(r);
2553                         j_ = gdl(s);
2554
2555                         % Si corresponden a grados de libertad -> puntos en (i,j)
2556                         % se suma contribucion metodo indicial
2557                         if (i_ ~= 0 && j_ ~= 0 && r == s)
2558                             analisisObj.Mt(i_, j_) = analisisObj.Mt(i_, j_) + m_elem(r);
2559                         end
2560
2561                     end % for s
2562                 end % for r
2563
2564             end % for i
2565
2566             % Masa de los elementos
2567             mElementos = sum(diag(analisisObj.Mt)) / 2;
2568
2569             % Agrega las cargas
2570             fprintf('\t\tAgrega masa de cargas\n');
2571             pat = analisisObj.modeloObj.obtenerPatronesDeCargas();
2572             for i = 1:length(pat)
2573
2574                 cargas = pat{i}.obtenerCargas();
2575                 for j = 1:length(cargas)
2576
2577                     % Si la carga ya sumo masa se bloquea
2578                     if ~cargas{j}.cargaSumaMasa()
2579                         continue;
2580                     end
2581
2582                     nodoCarga = cargas{j}.obtenerNodos();
2583                     m = cargas{j}.obtenerMasa();
2584
2585                     % Recorre los nodos
2586                     for k = 1:length(nodoCarga)
2587
2588                         n = nodoCarga{i}.obtenerGDLID();
2589                         analisisObj.Mt(n(1), n(1)) = analisisObj.Mt(n(1), n(1)) + 0.5 * m;
2590                         analisisObj.Mt(n(2), n(2)) = analisisObj.Mt(n(2), n(2)) + 0.5 * m;
2591                         if length(n) == 3
2592                             analisisObj.Mt(n(3), n(3)) = analisisObj.Mt(n(3), n(3)) + 1e-6;
2593                         end
2594                         % u(3) no se agrega dado que es el giro
2595
2596                     end % for k
2597
2598                     % Bloquea la suma de masa de esta carga
2599                     cargas{j}.bloquearCargaMasa();
2600
2601                 end % for j
2602
2603             end % for i
2604
2605             % Masa total
2606             mTotal = sum(diag(analisisObj.Mt)) / 2;
2607
2608             % Masa de las cargas
2609             mCargas = mTotal - mElementos;
2610
2611             % Despliega informacion
2612             fprintf('\tDistribucion de masa\n');
2613             fprintf('\t\tMasa de elementos: %.1f (%.2f%%)\n', mElementos, ...
2614                 mElementos/mTotal*100);
2615             fprintf('\t\tMasa de cargas: %.1f (%.2f%%)\n', mCargas, ...
2616                 mCargas/mTotal*100);
2617             fprintf('\t\tMasa total: %.1f\n', mTotal);
2618
2619         end % ensamblarMatrizMasa function
2620
2621         function Cdv = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
2622             % ensamblarMatrizRigidez: es un metodo de la clase ModalEspectral
2623             % que se usa para realizar el armado de la matriz de
2624             % amortiguamiento de los disipadores del modelo
2625             %
2626             % Cdv = ensamblarMatrizAmortiguamientoDisipadores(analisisObj)
2627             %
2628             % Ensambla la matriz de rigidez del modelo analizado usando el metodo
2629             % indicial
2630
2631             % fprintf('\tEnsamblando matriz de amortiguamiento disipadores\n');
2632             ndglc = analisisObj.numeroGDL - analisisObj.gdlCond; % Numero de grados de libertad condensados
2633             Cdv = zeros(ndglc, ndglc);
2634
2635             % Extraemos los Elementos
2636             disipadorObjetos = analisisObj.modeloObj.obtenerDisipadores();
2637             numeroDisipadores = length(disipadorObjetos);
2638
2639             % Definimos los GDLID en los elementos
2640             for i = 1:numeroDisipadores
2641
2642                 % Se obienen los gdl del elemento metodo indicial
2643                 gdl = disipadorObjetos{i}.obtenerGDLIDCondensado();
2644                 ngdl = disipadorObjetos{i}.obtenerNumeroGDL();
2645
2646                 % Se obtiene la matriz de amortiguamiento global del elemento-i
2647                 c_globl_elem = disipadorObjetos{i}.obtenerMatrizAmortiguamientoCoordGlobal();
2648
2649                 % Se calcula el metodo indicial
2650                 for r = 1:ngdl
2651                     for s = 1:ngdl
2652                         i_ = gdl(r);
2653                         j_ = gdl(s);
2654
2655                         % Si corresponden a grados de libertad -> puntos en (i,j)
2656                         % se suma contribucion metodo indicial
2657                         if (i_ ~= 0 && j_ ~= 0)
2658                             Cdv(i_, j_) = Cdv(i_, j_) + c_globl_elem(r, s);
2659                         end
2660
2661                     end % for s
2662                 end % for r
2663
2664             end % for i
2665
2666         end % ensamblarMatrizAmortiguamientoDisipadores function
2667
2668         function Kdv = ensamblarMatrizRigidezDisipadores(analisisObj)
2669             % ensamblarMatrizRigidezDisipadores: es un metodo de la clase
2670             % ModalEspectral que se usa para realizar el armado de la matriz
2671             % de rigidez del modelo analizado
2672             %
2673             % Kdv = ensamblarMatrizRigidezDisipadores(analisisObj)
2674             %
2675             % Ensambla la matriz de rigidez de los disipadores del modelo
2676             % analizado usando el metodo indicial
2677
2678             % fprintf('\tEnsamblando matriz de rigidez disipadores\n');
2679             ndglc = analisisObj.numeroGDL - analisisObj.gdlCond; % Numero de grados de libertad condensados
2680             Kdv = zeros(ndglc, ndglc);
2681
2682             % Extraemos los elementos
2683             disipadorObj = analisisObj.modeloObj.obtenerDisipadores();
2684             numeroDisipadores = length(disipadorObj);
2685
2686             % Definimos los GDLID en los elementos
2687             for i = 1:numeroDisipadores
2688
2689                 % Se obienen los gdl del elemento metodo indicial
2690                 gdl = disipadorObj{i}.obtenerGDLIDCondensado();
2691                 ngdl = disipadorObj{i}.obtenerNumeroGDL();
2692
2693                 % Se obtiene la matriz de amortiguamiento global del elemento-i
2694                 k_globl_elem = disipadorObj{i}.obtenerMatrizRigidezCoordGlobal();
2695
2696                 % Se calcula el metodo indicial
2697                 for r = 1:ngdl
2698                     for s = 1:ngdl
2699                         i_ = gdl(r);
2700                         j_ = gdl(s);
2701
2702                         % Si corresponden a grados de libertad -> puntos en (i,j)
2703                         % se suma contribucion metodo indicial
2704                         if (i_ ~= 0 && j_ ~= 0)
2705                             Kdv(i_, j_) = Kdv(i_, j_) + k_globl_elem(r, s);
2706                         end
2707
2708                     end % for s
2709                 end % for r
2710
2711             end % for i
2712
2713         end % ensamblarMatrizAmortiguamientoDisipadores function
2714
2715         function ensamblarVectorFuerzas(analisisObj)
2716             % ensamblarVectorFuerzas: es un metodo de la clase ModalEspectral que se usa para
2717             % realizar el armado del vector de fuerzas del modelo analizado
2718             %
2719             % ensamblarVectorFuerzas(analisisObj)
2720             %
2721             % Ensambla el vector de fuerzas del modelo analizado usando el metodo
2722             % indicial
2723
2724             analisisObj.F = zeros(analisisObj.numeroGDL, 1);
2725
2726             % En esta funcion se tiene que ensamblar el vector de fuerzas
2727             % Extraemos los nodos
2728             nodoObjetos = analisisObj.modeloObj.obtenerNodos();
2729             numeroNodos = length(nodoObjetos);
2730
2731             % Definimos los GDLID en los nodos
2732             for i = 1:numeroNodos
2733
2734                 ngdlid = nodoObjetos{i}.obtenerNumeroGDL(); % Numero grados de libertad del nodo
2735                 gdl = nodoObjetos{i}.obtenerGDLID(); % Grados de libertad del nodo
2736                 reacc = nodoObjetos{i}.obtenerReacciones(); % Reacciones del nodo
2737
2738                 % Recorre cada grado de libertad, si no es cero entonces
2739                 % hay una carga aplicada en ese grado de libertad para
2740                 % lograr el equilibrio
2741                 for j = 1:ngdlid
2742                     if (gdl(j) ~= 0)
2743                         analisisObj.F(gdl(j)) = -reacc(j);
2744                     end
2745                 end % for j
2746
2747             end % for i
2748
2749         end % ensamblarVectorFuerzas function
2750
2751         function plotAnimado(analisisObj, deformada, modo, factor, phif, limx, limy, limz, ...
2752                 per, cuadro, totCuadros, defElem, defCarga, carga, tcarga, tcargaEq, ...
2753                 mostrarEstatico, mostrarDisipadores, styleNodoE, sizeNodoE, ...
2754                 styleNodoD, sizeNodoD, styleElemE, lwElemE, styleElemD, lwElemD, ...
2755                 styleDisipador, colorDisipador, lwDisipador, unidad, ...
2756                 angAzh, angPol)
2757             % plotAnimado: Anima el grafico en funcion del numero del modo
2758
2759             % Si se grafica la carga no se aplica el factor sin(wt)
2760             if defCarga
2761                 phif = 1;
2762             end
2763
2764             % Carga objetos
2765             nodoObjetos = analisisObj.modeloObj.obtenerNodos();
2766             numeroNodos = length(nodoObjetos);
2767
2768             % Obtiene cuantos GDL tiene el modelo
2769             gdl = 2;
2770             ngdl = analisisObj.modeloObj.obtenerNumeroDimensiones();
2771             j = 1;
2772             for i = 1:numeroNodos
2773                 coords = nodoObjetos{i}.obtenerCoordenadas();
2774                 ngdlid = length(coords);
2775                 gdl = max(gdl, ngdlid);
2776                 if ~deformada && mostrarEstatico
2777                     if modo ~= 0 || defCarga
2778                         nodoObjetos{i}.plot([], styleNodoE, sizeNodoE);
2779                     else
2780                         nodoObjetos{i}.plot([], styleNodoD, sizeNodoD);
2781                     end
2782                     if j == 1
2783                         hold on;
2784                     end
2785                     j = j + 1;
2786                 end
2787             end % for i
2788
2789             % Grafica los elementos
2790             elementoObjetos = analisisObj.modeloObj.obtenerElementos();
2791             numeroElementos = length(elementoObjetos);
2792             for i = 1:numeroElementos
2793
2794                 % Se obienen los gdl del elemento metodo indicial
2795                 nodoElemento = elementoObjetos{i}.obtenerNodos();
2796                 numNodo = length(nodoElemento);
2797
2798                 if (~deformada || analisisObj.mostrarDeformada) && mostrarEstatico
2799                     if modo ~= 0 || defCarga
2800                         elementoObjetos{i}.plot({}, styleElemE, lwElemE, false);
2801                     else
2802                         elementoObjetos{i}.plot({}, styleElemD, lwElemD, false);
2803                     end
2804                 end
2805
2806                 if deformada
2807                     def = cell(numNodo, 1);
2808                     for j = 1:numNodo
2809                         def{j} = factor * phif * analisisObj.obtenerDeformadaNodo(nodoElemento{j}, ...
2810                             modo, analisisObj.numDGReal, defCarga, carga, tcarga);
2811                     end % for j
2812                     elementoObjetos{i}.plot(def, styleElemD, lwElemD, defElem);
2813                     if i == 1
2814                         hold on;
2815                     end
2816                 end
2817
2818             end % for i
2819
2820             % Grafica los nodos deformados
2821             if deformada
2822                 for i = 1:numeroNodos
2823                     coords = nodoObjetos{i}.obtenerCoordenadas();
2824                     ngdlid = length(coords);
2825                     gdl = max(gdl, ngdlid);
2826                     def = analisisObj.obtenerDeformadaNodo(nodoObjetos{i}, modo, ...
2827                         gdl, defCarga, carga, tcarga);
2828                     nodoObjetos{i}.plot(def.*factor*phif, styleNodoD, sizeNodoD);
2829                 end % for i
2830             end
2831
2832             % Grafica los disipadores
2833             if mostrarDisipadores
2834                 disipadores = analisisObj.modeloObj.obtenerDisipadores();
2835                 for i = 1:length(disipadores)
2836                     nodoDisipador = disipadores{i}.obtenerNodos();
2837                     numnodoDisipador = disipadores{i}.obtenerNumeroNodos();
2838                     def = cell(numnodoDisipador, 1);
2839                     for j = 1:numnodoDisipador
2840                         def{j} = factor * phif * analisisObj.obtenerDeformadaNodo(nodoDisipador{j}, ...
2841                             modo, analisisObj.numDGReal, defCarga, carga, tcarga);
2842                     end % for j
2843                     disipadores{i}.plot(def, styleDisipador, lwDisipador, colorDisipador);
2844                 end % for i
2845             end
2846
2847             % Setea el titulo
2848             if ~defCarga % Se grafica los modos
2849                 if ~deformada
2850                     title('Analisis modal espectral');
2851                 else
2852                     a = sprintf('Analisis modal espectral - Modo %d (T: %.3fs)', modo, per);
2853                     if totCuadros > 1
2854                         b = sprintf('Escala deformacion x%d - Cuadro %s/%d', ...
2855                             factor, padFillNum(cuadro, totCuadros), totCuadros);
2856                     else
2857                         b = sprintf('Escala deformacion x%d', factor);
2858                     end
2859                     title({a; b});
2860                 end
2861             else % Grafica una carga
2862                 a = sprintf('Analisis modal espectral - Carga %s', carga.obtenerEtiqueta());
2863                 b = sprintf('Escala deformacion x%d - Cuadro %s/%d - t:%.3fs', ...
2864                     factor, padFillNum(cuadro, totCuadros), totCuadros, tcargaEq(cuadro));
2865                 title({a; b});
2866             end
2867             grid on;
2868
2869             % Limita en los ejes
2870             if deformada || modo == 0
2871                 if limx(1) < limx(2)
2872                     xlim(limx);
2873                 end
2874                 if limy(1) < limy(2)
2875                     ylim(limy);
2876                 end
2877                 if gdl == 3 && limz(1) < limz(2)
2878                     zlim(limz);
2879                 end
2880             end
2881
2882             if ngdl == 2
2883                 xlabel(sprintf('X (%s)', unidad));
2884                 ylabel(sprintf('Y (%s)', unidad));
2885             else
2886                 xlabel(sprintf('X (%s)', unidad));
2887                 ylabel(sprintf('Y (%s)', unidad));
2888                 zlabel(sprintf('Z (%s)', unidad));
2889                 view(angAzh, angPol);
2890             end
2891
2892         end % plotAnimado function
2893
2894         function [limx, limy, limz] = obtenerLimitesDeformada(analisisObj, modo, factor, defcarga, carga)
2895             % obtenerLimitesDeformada: Obtiene los limites de deformacion
2896             %
2897             % obtenerLimitesDeformada(analisisObj,modo,factor,defcarga,carga)
2898
2899             fprintf('\tCalculando los limites del grafico\n');
2900             factor = 2.5 * factor;
2901             limx = [inf, -inf];
2902             limy = [inf, -inf];
2903             limz = [inf, -inf];
2904
2905             % Carga objetos
2906             nodoObjetos = analisisObj.modeloObj.obtenerNodos();
2907             numeroNodos = length(nodoObjetos);
2908             gdl = 2;
2909             for i = 1:numeroNodos
2910                 coords = nodoObjetos{i}.obtenerCoordenadas();
2911                 ngdlid = length(coords);
2912                 gdl = max(gdl, ngdlid);
2913             end % for i
2914
2915             elementoObjetos = analisisObj.modeloObj.obtenerElementos();
2916             numeroElementos = length(elementoObjetos);
2917             for i = 1:numeroElementos
2918                 nodoElemento = elementoObjetos{i}.obtenerNodos();
2919                 numNodo = length(nodoElemento);
2920                 for j = 1:numNodo
2921                     coord = nodoElemento{j}.obtenerCoordenadas();
2922                     if (analisisObj.analisisFinalizado && modo > 0) || defcarga
2923                         def = analisisObj.obtenerDeformadaNodo(nodoElemento{j}, modo, gdl, defcarga, carga, -1);
2924                         coordi = coord + def .* factor;
2925                     else
2926                         coordi = coord;
2927                     end
2928                     limx(1) = min(limx(1), coordi(1));
2929                     limy(1) = min(limy(1), coordi(2));
2930                     limx(2) = max(limx(2), coordi(1));
2931                     limy(2) = max(limy(2), coordi(2));
2932                     if gdl == 3
2933                         limz(1) = min(limz(1), coordi(3));
2934                         limz(2) = max(limz(2), coordi(3));
2935                     end
2936                     if (analisisObj.analisisFinalizado && modo > 0) || defcarga
2937                         coordf = coord - def .* factor;
2938                     else
2939                         coordf = coord;
2940                     end
2941                     limx(1) = min(limx(1), coordf(1));
2942                     limy(1) = min(limy(1), coordf(2));
2943                     limx(2) = max(limx(2), coordf(1));
2944                     limy(2) = max(limy(2), coordf(2));
2945                     if gdl == 3
2946                         limz(1) = min(limz(1), coordf(3));
2947                         limz(2) = max(limz(2), coordf(3));
2948                     end
2949                 end % for j
2950             end % for i
2951
2952         end % obtenerLimitesDeformada function
2953
2954         function def = obtenerDeformadaNodo(analisisObj, nodo, modo, gdl, defcarga, carga, tcarga)
2955             % obtenerDeformadaNodo: Obtiene la deformada de un nodo
2956             %
2957             % obtenerDeformadaNodo(analisisObj,nodo,modo,gdl,defcarga,carga,tcarga)
2958
2959             ngdl = nodo.obtenerGDLIDCondensado();
2960             def = zeros(gdl, 1);
2961             gdl = min(gdl, length(ngdl));
2962             for i = 1:gdl
2963                 if ngdl(i) > 0
2964                     if ~defcarga % La deformada la saca a partir del modo
2965                         if modo > 0
2966                             def(i) = analisisObj.phin(ngdl(i), modo);
2967                         else
2968                             def(i) = 0;
2969                         end
2970                     else
2971                         def(i) = carga.obtenerDesplazamientoTiempo(ngdl(i), tcarga);
2972                     end
2973                 else
2974                     def(i) = 0;
2975                 end
2976             end % for i
2977
2978         end % obtenerDeformadaNodo function
2979
2980         function [Cortante, Momento, CBplot, MBplot, hplot] = calcularMomentoCorteBasalAcel(analisisObj, acel)
2981             % calcularMomentoCorteBasalAcel: Calcula el momento y corte
2982             % basal en funcion de una aceleracion
2983             %
2984             % [Cortante,Momento,CBplot,MBplot,hplot] = calcularMomentoCorteBasalAcel(analisisObj,acel)
2985             %
2986             % Se genera vector en que las filas contienen nodos en un mismo piso,
2987             % rellenando con ceros la matriz en caso de diferencia de nodos por piso.
2988             % Tambien se genera vector que contiene alturas de piso
2989
2990             % Iniciando el proceso
2991             nodos = analisisObj.modeloObj.obtenerNodos();
2992             nnodos = length(nodos);
2993
2994             habs = zeros(1, 1);
2995             hNodos = zeros(1, 1);
2996             j = 1;
2997             k = 1;
2998             ini = 1;
2999             for i = 1:nnodos
3000                 CoordNodo = nodos{i}.obtenerCoordenadas;
3001                 yNodo = CoordNodo(2);
3002                 if yNodo ~= habs(j)
3003                     k = 1;
3004                     j = j + 1;
3005                     habs(j, 1) = yNodo;
3006                     hNodos(j, k) = i;
3007                 elseif i == 1
3008                     hNodos(j, k) = i;
3009                 else
3010                     k = k + 1;
3011                     hNodos(j, k) = i;
3012                 end
3013                 if yNodo == 0
3014                     ini = ini + 1;
3015                 end
3016             end % for i
3017
3018             [~, s] = size(acel);
3019             M = analisisObj.obtenerMatrizMasa();
3020             m = zeros(nnodos-ini+1, 1);
3021             acelx = zeros(nnodos-ini+1, s);
3022             Fnodos = zeros(nnodos-ini+1, s);
3023             Fpisos = zeros(length(habs)-1, s);
3024
3025             % Calculo de fuerzas inerciales nodales que generan corte, fuerzas nodales
3026             % y fuerzas por piso
3027             for i = ini:nnodos
3028                 gdls = nodos{i}.obtenerGDLIDCondensado();
3029                 gdlx = gdls(1);
3030                 acelx(i-ini+1, :) = acel(gdlx, :);
3031                 m(i-ini+1, 1) = M(gdlx, gdlx);
3032                 Fnodos(i-ini+1, :) = M(gdlx, gdlx) .* acel(gdlx, :);
3033                 [fil, ~] = find(hNodos == i);
3034                 Fpisos(fil-1, :) = Fpisos(fil-1, :) + Fnodos(i-ini+1, :);
3035             end % for i
3036
3037             % Calculo de cortante y momento acumulado por piso
3038             Fpisos_ud = flipud(Fpisos);
3039             habs_ud = flipud(habs);
3040             Cortante = zeros(length(habs)-1, s);
3041             Momento = zeros(length(habs)-1, s);
3042             for i = 1:length(habs) - 1
3043                 hcero = habs_ud(i+1);
3044                 for j = 1:i
3045                     Cortante(i, :) = Cortante(i, :) + Fpisos_ud(j, :);
3046                     Momento(i, :) = Momento(i, :) + Fpisos_ud(j, :) .* (habs_ud(j) - hcero);
3047                 end % for j
3048             end % for i
3049
3050             % Determinacion de envolvente maxima de cortante y momento basal
3051             icor = 1;
3052             imom = 1;
3053             CorB_max = 1;
3054             MomB_max = 1;
3055             [nfil, ~] = size(Cortante);
3056             for i = 1:s
3057                 if abs(Cortante(nfil, i)) > abs(CorB_max)
3058                     icor = i;
3059                     CorB_max = Cortante(nfil, i);
3060                 end
3061                 if abs(Momento(nfil, i)) > abs(MomB_max)
3062                     imom = i;
3063                     MomB_max = Momento(nfil, i);
3064                 end
3065             end % for i
3066
3067             % Calcula las envolventes, aplica valor absoluto
3068             VecCB = abs(Cortante(:, icor));
3069             VecMB = abs(Momento(:, imom));
3070             hgen = habs_ud;
3071             hplot = zeros(2*length(hgen), 1);
3072             CBplot = zeros(2*length(hgen)-1, 1);
3073             MBplot = zeros(2*length(hgen)-1, 1);
3074             aux1 = 1;
3075             aux2 = 2;
3076             for i = 1:length(hgen)
3077                 hplot(aux1, 1) = hgen(i);
3078                 hplot(aux1+1, 1) = hgen(i);
3079                 if aux2 <= 2 * length(hgen) - 1
3080                     CBplot(aux2, 1) = VecCB(i);
3081                     CBplot(aux2+1, 1) = VecCB(i);
3082                     MBplot(aux2, 1) = VecMB(i);
3083                     MBplot(aux2+1, 1) = VecMB(i);
3084                 end
3085                 aux1 = aux1 + 2;
3086                 aux2 = aux2 + 2;
3087             end % for i
3088             hplot(length(hplot)) = [];
3089
3090         end % calcularMomentoCorteBasalAcel function
3091
3092         function ctitle = imprimirPropiedadesAnalisisCarga(analisisObj, carga) %#ok<INUSL>
3093             % imprimirPropiedadesAnalisisCarga: Imprime propiedades de
3094             % analisis de la carga o combinacion de cargas
3095             %
3096             % ctitle = imprimirPropiedadesAnalisisCarga(analisisObj, carga)
3097
3098             ctitle = 'Carga';
3099             if isa(carga, 'CombinacionCargas')
3100                 ctitle = 'Combinacion';
3101             end
3102             fprintf('\t%s %s\n', ctitle, carga.obtenerEtiqueta());
3103
3104             if carga.usoAmortiguamientoRayleigh()
3105                 fprintf('\t\tLa %s se calculo con amortiguamiento Rayleigh\n', lower(ctitle));
3106             else
3107                 fprintf('\t\tLa %s se calculo con amortiguamiento de Wilson-Penzien\n', lower(ctitle));
3108             end
3109
3110             if carga.usoDescomposicionModal()
3111                 fprintf('\t\tLa %s se calculo usando descomposicion modal\n', lower(ctitle));
3112             else
3113                 fprintf('\t\tLa %s se calculo sin usar descomposicion modal\n', lower(ctitle));
3114             end
3115
3116         end % imprimirPropiedadesAnalisisCarga function
3117
3118     end % methods(private) ModalEspectral
3119
3120 end % class ModalEspectral