Description of tukeywin
tukeywin
PURPOSE
tukeywin: Tukey window.
SYNOPSIS
function w = tukeywin(n, r)
DESCRIPTION
 tukeywin: Tukey window.
 Author: Pablo Pizarro @ppizarror.com, 2017.
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
CROSS-REFERENCE INFORMATION
This function calls:
check_order check_order: Checks the order passed to the window functions.
This function is called by:
ModalEspectral |______________________________________________________________________|
PSD PSD: Power Spectral Density. Calcula la FFT de un registro sismico
norm_spectrogram NORMSPECTROGRAM This function create a normalized spectrogram matrix by