Description of calculoLDV
calculoLDV
PURPOSE
calculoLDV: Esta funcion genera los vectores de Ritz Dependientes de la
SYNOPSIS
function [phi, wn] = calculoLDV(M, K, F, nritz)
DESCRIPTION
 calculoLDV: Esta funcion genera los vectores de Ritz Dependientes de la
 carga
 [phi,T] = calculoLDV(M , K , F , nritz)
 Parametros:
   M, K        Matriz masa y rigidez
   F           Matriz cuyas columnas son vectores de forma de las cargas
               externas
   nritz       Numero de vectores de Ritz a obtener para cada condicion de
               carga
 Salida:
   w           Matriz vectores propios
   v           Valores propios
CROSS-REFERENCE INFORMATION
This function calls:
GSM GSM: Gram - Shmidt Modificado
modonorm modonorm: Normaliza formas modales
This function is called by:
ModalEspectral |______________________________________________________________________|