Description of dispMetodoTEFAME
dispMetodoTEFAME
PURPOSE
dispMetodoTEFAME: Normaliza la salida estandar disp en consola de los
SYNOPSIS
function dispMetodoTEFAME()
DESCRIPTION
 dispMetodoTEFAME: Normaliza la salida estandar disp en consola de los
 metodos usados por las clases de TEFAME
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AnalisisEstatico |______________________________________________________________________|
ModalEspectral |______________________________________________________________________|
Modelo |______________________________________________________________________|
CombinacionCargas |______________________________________________________________________|
CargaGenerica |______________________________________________________________________|
CargaPulso |______________________________________________________________________|
CargaRegistroSismico |______________________________________________________________________|
CargaSinusoidal |______________________________________________________________________|
CargaBielaTemperatura |______________________________________________________________________|
CargaMembrana2DDistribuida |______________________________________________________________________|
CargaNodo |______________________________________________________________________|
CargaViga2DDistribuida |______________________________________________________________________|
CargaViga2DPuntual |______________________________________________________________________|
CargaVigaColumna2DDistribuida |______________________________________________________________________|
CargaVigaColumna2DPuntual |______________________________________________________________________|
CargaVigaColumna3DDistribuida |______________________________________________________________________|
PatronDeCargasConstante |______________________________________________________________________|
PatronDeCargasDinamico |______________________________________________________________________|
DisipadorFriccionalPuro2D |______________________________________________________________________|
DisipadorTriangular2D |______________________________________________________________________|
DisipadorViscoso2D |______________________________________________________________________|
Biela2D |______________________________________________________________________|
Fundacion2D |______________________________________________________________________|
Membrana2D |______________________________________________________________________|
Viga2D |______________________________________________________________________|
VigaColumna2D |______________________________________________________________________|
Biela3D |______________________________________________________________________|
VigaColumna3D |______________________________________________________________________|
Nodo |______________________________________________________________________|
RestriccionNodo |______________________________________________________________________|