Description of PSD
PSD
PURPOSE
PSD: Power Spectral Density. Calcula la FFT de un registro sismico
SYNOPSIS
function [f, psd, fft, fftcomp, envFormaModal, tlocMean, tlocStd, locMean,locStd, locFreq, maxlocs, pks, betaNodo, betaFreqNodo, fftmean, fftstd,psdmean, psdstd] = PSD(a, fs, gdl, varargin)
DESCRIPTION
 PSD: Power Spectral Density. Calcula la FFT de un registro sismico
 analizado para varios nodos con distintos grados de libertad. La funcion
 permite calcular distintos tipos de periodos naturales, arrojando un
 vector. Adicionalmente se calcula una razon de amortiguamiento con cada
 modo.
 Input:
   a               Registro de aceleracion
   fs              Factor de muestreo del registro
   gdl             Vector con los grados de libertad de los nodos en el analisis
 Parametros opcionales:
   betaFFT         Realiza el calculo del amortiguamiento con FFT o PSD
   betaFFTMax      El amortiguamiento se calcula con el maximo FFT de todos los nodos
   peakFFT         Realiza el calculo de peaks con FFT o PSD
   peakMinDistance Distancia minima entre peaks requerida
   tukeywinr       Factor de la ventana de tukey
   zerofill        Indica relleno de ceros para FFT
 Output:
   f               Vector de frecuencias
   psd             Cell PSD de cada registro de los nodos
   fft             Cell FFT de cada registro de los nodos
   fftcomp         Registro completo (Re+Im)
   envFormaModal   Cell con formas modales para cada periodo
   tlocMean        Periodos medios de cada modo obtenidos de los peaks
   tlocStd         Desviacion estandar de cada modo obtenido de los peaks
   locMean         Frecuencia media de cada modo obtenido en los peaks
   locStd          Desviacion estandar de la frecuencia de cada modo
   locFreq         Posicion en el vector de frecuencias de cada modo
   maxlocs         Numero de modos encontrados en los peaks
   pks             Vector de peaks
   betaNodo        Vector de amortiguamientos por cada modo
   betaFreqNodo    Valor del FFT objetivo por cada amortiguamiento modal
   fftmean         Promedios FFT
   fftstd          Desviacion estandar FFT
   psdmean         Promedios PSD
   psdstd          Desviacion estandar PSD
CROSS-REFERENCE INFORMATION
This function calls:
DFT DFT: Determina la Transformada discreta de Fourier de una senal
tukeywin tukeywin: Tukey window.
This function is called by:
ModalEspectral |______________________________________________________________________|