Description of Elemento
Elemento
PURPOSE
______________________________________________________________________
SYNOPSIS
This is a script file.
DESCRIPTION
 ______________________________________________________________________
|                                                                      |
|           TEFAME - Toolbox para Elemento Finitos y Analisis          |
|                  Matricial de Estructuras en MATLAB                  |
|                                                                      |
|                   Area  de Estructuras y Geotecnia                   |
|                   Departamento de Ingenieria Civil                   |
|              Facultad de Ciencias Fisicas y Matematicas              |
|                         Universidad de Chile                         |
|                                                                      |
| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
| visualizar  la respuesta de sistemas  estructurales usando el metodo |
| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
| La plataforma es desarrollada en  propagacion orientada a objetos en |
| MATLAB.                                                              |
|______________________________________________________________________|
 ______________________________________________________________________
|                                                                      |
| Clase Elemento                                                       |
|                                                                      |
| Este archivo contiene la definicion de la Clase Elemento             |
| Elemento es una subclase de la  clase ComponenteModelo y corresponde |
| a  la representacion  abstracta  de los elementos en  el  metodo  de |
| elementos finitos o analisis matricial de estructuras.               |
| La clase Elemento se usa como una superclase para todos los tipos de |
| elementos que hay en la plataforma. Y define los metodos minimos que |
| tiene que ser implementados en cada subclase                         |
|                                                                      |
| Programado: FR                                                       |
| Fecha: 05/08/2015                                                    |
|                                                                      |
| Modificado por: FR - 24/10/2016                                      |
|                 Pablo Pizarro @ppizarror - 10/04/2019                |
|______________________________________________________________________|
  Properties (Access=private):
  Methods:
       elementoObj = Elemento(etiquetaElemento)
       numeroNodos = obtenerNumeroNodos(elementoObj)
       nodosElemento = obtenerNodos(elementoObj)
       numeroGDL = obtenerNumeroGDL(elementoObj)
       gdlID = obtenerGDL(elementoObj)
       k_global = obtenerMatrizRigidezCoordGlobal(elementoObj)
       k_local = obtenerMatrizRigidezCoordLocal(elementoObj)
       fr_global = obtenerFuerzaResistenteCoordGlobal(elementoObj)
       fr_local = obtenerFuerzaResistenteCoordLocal(elementoObj)
       inicializar(elementoObj)
       definirGDLID(elementoObj)
       agregarFuerzaResistenteAReacciones(elementoObj)
       actualizar(elementoObj)
       guardarPropiedades(elementoObj,archivoSalidaHandle)
       guardarEsfuerzosInternos(elementoObj,archivoSalidaHandle)
       activarGraficoDeformada(elementoObj)
       desactivarGraficoDeformada(elementoObj)
       graficaDeformada(elementoObj)
       disp(elementoObj)
  Methods SuperClass (ComponenteModelo):
       etiqueta = obtenerEtiqueta(componenteModeloObj)
       e = equals(componenteModeloObj,obj)
       objID = obtenerIDObjeto(componenteModeloObj)
CROSS-REFERENCE INFORMATION
This function calls:
ComponenteModelo ______________________________________________________________________
Elemento ______________________________________________________________________
This function is called by:
Biela2D ______________________________________________________________________
Biela3D ______________________________________________________________________
Elemento ______________________________________________________________________
Membrana ______________________________________________________________________
Viga2D ______________________________________________________________________
VigaColumna2D ______________________________________________________________________
SUBFUNCTIONS
function elementoObj = Elemento(etiquetaElemento)
function numeroNodos = obtenerNumeroNodos(elementoObj)
function nodosElemento = obtenerNodos(elementoObj)
function numeroGDL = obtenerNumeroGDL(elementoObj)
function gdlID = obtenerGDL(elementoObj)
function k_global = obtenerMatrizRigidezCoordGlobal(elementoObj)
function k_local = obtenerMatrizRigidezCoordLocal(elementoObj)
function fr_global = obtenerFuerzaResistenteCoordGlobal(elementoObj)
function fr_local = obtenerFuerzaResistenteCoordLocal(elementoObj)
function inicializar(elementoObj)
function definirGDLID(elementoObj)
function agregarFuerzaResistenteAReacciones(elementoObj)
function actualizar(elementoObj)
function guardarPropiedades(elementoObj, archivoSalidaHandle)
function guardarEsfuerzosInternos(elementoObj, archivoSalidaHandle)
function plot(elementoObj, deformadas, tipoLinea, grosorLinea, gdl)
function activarGraficoDeformada(elementoObj)
function desactivarGraficoDeformada(elementoObj)
function def = graficaDeformada(elementoObj)
function graficarLinea(elementoObj, coord1, coord2, tipoLinea, grosorLinea)
function disp(elementoObj)
function definirFactorUnidadMasa(elementoObj, factor)
SOURCE CODE
% ______________________________________________________________________
%|                                                                      |
%|           TEFAME - Toolbox para Elemento Finitos y Analisis          |
%|                  Matricial de Estructuras en MATLAB                  |
%|                                                                      |
%|                   Area  de Estructuras y Geotecnia                   |
%|                   Departamento de Ingenieria Civil                   |
%|              Facultad de Ciencias Fisicas y Matematicas              |
%|                         Universidad de Chile                         |
%|                                                                      |
%| TEFAME es una  plataforma en base a objetos para modelar, analizar y |
%| visualizar  la respuesta de sistemas  estructurales usando el metodo |
%| de elementos finitos y analisis matricial de estructuras en MATLAB.  |
%| La plataforma es desarrollada en  propagacion orientada a objetos en |
%| MATLAB.                                                              |
%|______________________________________________________________________|
% ______________________________________________________________________
%|                                                                      |
%| Clase Elemento                                                       |
%|                                                                      |
%| Este archivo contiene la definicion de la Clase Elemento             |
%| Elemento es una subclase de la  clase ComponenteModelo y corresponde |
%| a  la representacion  abstracta  de los elementos en  el  metodo  de |
%| elementos finitos o analisis matricial de estructuras.               |
%| La clase Elemento se usa como una superclase para todos los tipos de |
%| elementos que hay en la plataforma. Y define los metodos minimos que |
%| tiene que ser implementados en cada subclase                         |
%|                                                                      |
%| Programado: FR                                                       |
%| Fecha: 05/08/2015                                                    |
%|                                                                      |
%| Modificado por: FR - 24/10/2016                                      |
%|                 Pablo Pizarro @ppizarror - 10/04/2019                |
%|______________________________________________________________________|
%
%  Properties (Access=private):
%  Methods:
%       elementoObj = Elemento(etiquetaElemento)
%       numeroNodos = obtenerNumeroNodos(elementoObj)
%       nodosElemento = obtenerNodos(elementoObj)
%       numeroGDL = obtenerNumeroGDL(elementoObj)
%       gdlID = obtenerGDL(elementoObj)
%       k_global = obtenerMatrizRigidezCoordGlobal(elementoObj)
%       k_local = obtenerMatrizRigidezCoordLocal(elementoObj)
%       fr_global = obtenerFuerzaResistenteCoordGlobal(elementoObj)
%       fr_local = obtenerFuerzaResistenteCoordLocal(elementoObj)
%       inicializar(elementoObj)
%       definirGDLID(elementoObj)
%       agregarFuerzaResistenteAReacciones(elementoObj)
%       actualizar(elementoObj)
%       guardarPropiedades(elementoObj,archivoSalidaHandle)
%       guardarEsfuerzosInternos(elementoObj,archivoSalidaHandle)
%       activarGraficoDeformada(elementoObj)
%       desactivarGraficoDeformada(elementoObj)
%       graficaDeformada(elementoObj)
%       disp(elementoObj)
%  Methods SuperClass (ComponenteModelo):
%       etiqueta = obtenerEtiqueta(componenteModeloObj)
%       e = equals(componenteModeloObj,obj)
%       objID = obtenerIDObjeto(componenteModeloObj)
classdef Elemento < ComponenteModelo
    properties(Access = private)
        graficaDeformadaElem % Grafica la deformada del elemento
    end % properties Elemento
    properties(Access = protected)
        factorMasa % Indica el factor en que convierte densidad en masa
    end % properties Elemento
    methods
        function elementoObj = Elemento(etiquetaElemento)
            % Elemento: es el constructor de la clase Elemento
            %
            % elementoObj = Elemento(etiquetaElemento)
            %
            % Crea un objeto de la clase Elemento, con un identificador unico
            % (etiquetaElemento)
            % Si no se pasan argumentos se crean vacios
            if nargin == 0
                etiquetaElemento = '';
            end % if
            % Llamamos al constructor de la SuperClass que es la clase ComponenteModelo
            elementoObj = elementoObj@ComponenteModelo(etiquetaElemento);
            elementoObj.graficaDeformadaElem = true;
        end % Elemento constructor
        function numeroNodos = obtenerNumeroNodos(elementoObj) %#ok<MANU>
            % obtenerNumeroNodos: es un metodo de la clase Elemento que se usa para
            % obtener el numero de nodos que tiene el Elemento
            %
            % numeroNodos = obtenerNumeroNodos(elementoObj)
            %
            % Entrega el numero de nodos (numeroNodos) que tiene el Elemento
            % (elementoObj)
            numeroNodos = 0;
        end % obtenerNumeroNodos function
        function nodosElemento = obtenerNodos(elementoObj) %#ok<MANU>
            % obtenerNodos: es un metodo de la clase Elemento que se usa para
            % obtener un arreglo con los nodos que tiene el Elemento
            %
            % nodosElemento = obtenerNumeroNodos(elementoObj)
            %
            % Entrega un arreglo con los Nodos (nodosElemento) que tiene el Elemento
            % (elementoObj)
            nodosElemento = [];
        end % obtenerNodos function
        function numeroGDL = obtenerNumeroGDL(elementoObj) %#ok<MANU>
            % obtenerNumeroGDL: es un metodo de la clase Elemento que se usa para
            % obtener el numero total de grados de libertad que tiene el Elemento
            %
            % numeroGDL = obtenerNumeroGDL(elementoObj)
            %
            % Entrega el numero de GDL (numeroGDL) que tiene el Elemento (elementoObj)
            numeroGDL = [];
        end % obtenerNumeroGDL function
        function gdlID = obtenerGDL(elementoObj) %#ok<MANU>
            % obtenerGDL: es un metodo de la clase Elemento que se usa para
            % obtener un arreglo con los ID de los grados de libertad que estan
            % asociados al Elemento
            %
            % gdlID = obtenerGDL(elementoObj)
            %
            % Entrega un arreglo con los ID de los GDL (gdlID) que tiene el Elemento
            % (elementoObj)
            gdlID = [];
        end % obtenerGDL function
        function k_global = obtenerMatrizRigidezCoordGlobal(elementoObj) %#ok<MANU>
            % obtenerMatrizRigidezCoordGlobal: es un metodo de la clase Elemento
            % que se usa para obtener la matriz de rigidez para el Elemento en el
            % sistema de coordenadas globales del sistema estructural o Modelo
            %
            % k_global = obtenerMatrizRigidezCoordGlobal(elementoObj)
            %
            % Entrega la matriz de rigidez (k_global) que tiene el Elemento (elementoObj)
            %  en el sistema de coordenadas globales
            k_global = [];
        end % obtenerMatrizRigidezGlobal function
        function k_local = obtenerMatrizRigidezCoordLocal(elementoObj) %#ok<MANU>
            % obtenerMatrizRigidezCoordLocal: es un metodo de la clase Elemento
            % que se usa para obtener la matriz de rigidez para el Elemento en el
            % sistema de coordenadas locales del elemento
            %
            % k_local = obtenerMatrizRigidezCoordLocal(elementoObj)
            %
            % Entrega la matriz de rigidez (k_local)  en el sistema de coordenadas
            % local que tiene el Elemento (elementoObj)
            k_local = [];
        end % obtenerMatrizRigidezLocal function
        function fr_global = obtenerFuerzaResistenteCoordGlobal(elementoObj) %#ok<MANU>
            % obtenerFuerzaResistenteCoordGlobal: es un metodo de la clase Elemento
            % que se usa para obtener el vector de fuerzas resitente del Elemento
            % en el sistema de coordenadas globales del modelo o sistema
            % estructural
            %
            % fr_global = obtenerFuerzaResistenteCoordGlobal(elementoObj)
            %
            % Entrega el vector con las fuerzas resistentes (fr_global) que tiene
            % elemento (elementoObj) en el sistema de coordenadas globales la
            % estructura
            fr_global = [];
        end % obtenerFuerzaResistenteCoordGlobal function
        function fr_local = obtenerFuerzaResistenteCoordLocal(elementoObj) %#ok<MANU>
            % obtenerFuerzaResistenteCoordLocal: es un metodo de la clase Elemento
            % que se usa para obtener el vector de fuerzas resitente del Elemento
            % en el sistema de coordenadas locales del elemento
            %
            % fr_local = obtenerFuerzaResistenteCoordLocal(elementoObj)
            %
            % Entrega el vector con las fuerzas resistentes (fr_local) que tiene
            % elemento (elementoObj) en el sistema de coordenadas locales del
            % elemento
            fr_local = [];
        end % obtenerFuerzaResistenteCoordLocal function
        function inicializar(elementoObj) %#ok<MANU>
            % inicializar: es un metodo de la clase Elemento que se usa para
            % inicializar las diferentes componentes que sean necesario en los
            % elementos para realizar posteriormente el analisis
            %
            % inicializar(elementoObj)
            %
            % Inicializa los diferentes componetes del Elemento (elementoObj),
            % para poder preparar estos para realizar el analisis
        end % inicializar function
        function definirGDLID(elementoObj) %#ok<MANU>
            % definirGDLID: es un metodo de la clase Elemento que se usa para
            % definir el vector con los ID de los GDL del elemento
            %
            % definirGDLID(elementoObj)
            %
            % Define los ID de los grados de libertad del Elemento (elementoObj)
        end % definirGDLID function
        function agregarFuerzaResistenteAReacciones(elementoObj) %#ok<MANU>
            % agregarEsfuerzosElementoAReaccion: es un metodo de la clase Nodo
            % que se usa para agregar el vector de fuerzas resistentes de un
            % elemento al nodo
            %
            % agregarEsfuerzosElementoAReaccion(nodoObj,esfuerzosElemento)
            %
            % Agrega al vector de reacciones del Nodo (nodoObj), el vector de
            % fuerzas resistente de un elemento entregados (cargaNodo)
        end % agregarFuerzaResistenteAReacciones function
        function actualizar(elementoObj) %#ok<MANU>
            % actualizar: es un metodo de la clase Elemento que se usa para
            % actualizar las diferentes componentes que sean necesario en los
            % elementos posterior a realizar el analisis
            %
            % actualizar(elementoObj)
            % Actualizar los diferentes componetes del Elemento (elementoObj),
            % despues de realizar el analisis
        end % actualizar function
        function guardarPropiedades(elementoObj, archivoSalidaHandle) %#ok<INUSD>
            % guardarPropiedades: es un metodo de la clase Elemento que se usa
            % para guardar en un archivo de salida las propiedades del Elemento
            %
            % guardarPropiedades(elementoObj,archivoSalidaHandle)
            %
            % Guarda las propiedades de los Elemento (elementoObj), en un archivo
            % de salida (archivoSalidaHandle)
        end % guardarPropiedades function
        function guardarEsfuerzosInternos(elementoObj, archivoSalidaHandle) %#ok<INUSD>
            % guardarEsfuerzosInternos: es un metodo de la clase Elemento que se
            % usa para guardar en un archivo de salida los esfuerzos internos del
            % Elemento
            %
            % guardarEsfuerzosInternos(elementoObj,archivoSalidaHandle)
            %
            % Guarda los esfuerzos internos de los Elemento (elementoObj), en un
            % archivo de salida (archivoSalidaHandle)
        end % guardarEsfuerzosInternos function
        function plot(elementoObj, deformadas, tipoLinea, grosorLinea, gdl) %#ok<INUSD>
            % plot: Grafica un elemento
            %
            % plot(elementoObj,deformadas,tipoLinea,grosorLinea,gdl)
        end % plot function
        function activarGraficoDeformada(elementoObj)
            % activarGraficoDeformada: Activa el grafico de la
            % deformada del elemento
            %
            % activarGraficoDeformada(elementoObj)
            elementoObj.graficaDeformadaElem = true;
        end % activarGraficoDeformada function
        function desactivarGraficoDeformada(elementoObj)
            % desactivarGraficoDeformada: Desactiva el grafico de la
            % deformada del elemento
            %
            % desactivarGraficoDeformada(elementoObj)
            elementoObj.graficaDeformadaElem = false;
        end % desactivarGraficoDeformada function
        function def = graficaDeformada(elementoObj)
            % graficaDeformada: Indica si el objeto grafica su deformada o
            % no
            %
            % def = graficaDeformada(elementoObj)
            def = elementoObj.graficaDeformadaElem;
        end % graficaDeformada function
        function graficarLinea(elementoObj, coord1, coord2, tipoLinea, grosorLinea) %#ok<INUSL>
            % graficarLinea: Grafica una linea para un elemento
            %
            % graficarLinea(elementoObj,coord1,coord2,tipoLinea,grosorLinea)
            if length(coord1) == 2
                plot([coord1(1), coord2(1)], [coord1(2), coord2(2)], tipoLinea, ...
                    'LineWidth', grosorLinea);
            else
                plot3([coord1(1), coord2(1)], [coord1(2), coord2(2)], [coord1(3), coord2(3)], ...
                    tipoLinea, 'LineWidth', grosorLinea);
            end
        end % graficarLinea function
        function disp(elementoObj)
            % disp: es un metodo de la clase Elemento que se usa para impimir en
            % command Window la informacion del Elemento
            %
            % disp(elementoObj)
            %
            % Imprime la informacion guardada en el Elemento (elementoObj) en
            % pantalla
            disp@ComponenteModelo(elementoObj);
            % No usar dispMetodoTEFAME()
        end % disp function
        function definirFactorUnidadMasa(elementoObj, factor)
            % definirFactorUnidadMasa: Funcion que define el cambio de
            % unidad para pasar masa carga a masa real
            %
            % definirFactorUnidadMasa(elementoObj,factor)
            elementoObj.factorMasa = factor;
        end % definirFactorUnidadMasa function
    end % methods Elemento
end % class Elemento